### ISSUE TITLE
Applying device parameters from Puavo

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#119]
Currently following device specific settings cannot be activated.
- [ ] Display drivers
- [ ] Display settings (xrandr)
- [ ] Allow guest login
- [ ] Device automatic shutdown options
- [ ] Audio output/input settings (pulseaudio)
- [ ] Device specific printers
- [ ] Default printer
- [ ] Image download rate limit
- [ ] Personal device
- [ ] Wlan accespoint channels
- [ ] Wlan accespoint reconf interval
- [ ] Wlan accespoint tx power
- [ ] Wlan accespoint report interval
- [ ] Wlan accespoint rssi kick intervel/treshold
- [ ] Wlan accespoint channels
- [ ] Screen backlight
- [ ] Activate jetpipe
- [ ] Activate Infotv/digital signage screen
- [ ] Enable xsessions
- [ ] Activate autopilot
- [ ] Webkiosk mode

**Comment by juhaerk** [comment]
The work for these has been mostly done, but we lack testing, and there are probably something still missing.

**Comment by juhaerk** [comment]
Closing this, this should work now. Not all settings have been tested yet, though.
