### ISSUE TITLE
"Cannot run" puavo-update-client due to missing path in PATH variable

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#124]
asokero@toimisto-videoedit-flyer:/var/lib/puavo-desktop/shared$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
asokero@toimisto-videoedit-flyer:/var/lib/puavo-desktop/shared$ /usr/sbin/puavo-update-client 
System update started.

**Comment by jarmopi** [comment]
Fixed by 1906a7122f072a1de08dcc071d9dc8502cbb2f5e.
