### ISSUE TITLE
"Could not lookup default puavoserver" while registering a new device.

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#125]
Lookup for default puavoserver does not seem to work when registering a new device booted from Trusty bootserver.

Image `opinsys-os-opinsysrestricted-stretch-2017-01-12-053647-amd64`

**Comment by juhaerk** [comment]
This got fixed as a side-effect in transition from init-puavo.d to puavo-conf scripts. /etc/resolv.conf settings we not right on netboot devices.
