### ISSUE TITLE
Using backspace to correct typos while registering

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#126]
To reproduce...
1. Boot a device to register screen
2. Proceed all the way to the part where register script asks for the new hostname
3. Write a hostname and the try to clear it with backspace.

This results that the character is cleared and at the same time the deleted character is also printed on the screen. This is confusing to the user.

**Comment by juhaerk** [comment]
I can no longer reproduce this issue with latest changes (setupcon and tmux changes).
