### ISSUE TITLE
Unable to run Steam client in Debian Stretch

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#141]
This is possibly due to clash with the bundled libraries (included in Steam client package).

**Comment by asokero** [comment]
I was able to make it work with some how-to/copypasteing/violance.
```
find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete
LIBGL_DRI3_DISABLE=1 steam
```

**Comment by juhaerk** [comment]
Actually I did not reproduce the problem, I just installed "steam"-package and it worked.  Is the problem with an old Steam installation, is this still reproducable?
