### ISSUE TITLE
Chrome and Chromium windows cannot be interracted with touchsreen

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#149]
Setting the browsers to use system titlebars is one workaround to this problem. Setting it system-wide to browsers is an another question.

**Comment by asokero** [comment]
```
{ ...
   "browser": {
      ...
      "custom_chrome_frame": true,
      ...
```
This seems to do the trick in users profile: `.config/google-chrome/Default/Preferences`

**Comment by juhaerk** [comment]
Done.
