### ISSUE TITLE
NW.js occationally reports about locked profile in login

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#159]
This happens on fatclients when changing from one device to another using the same username (not necessary simultaneously).

**Comment by jarmopi** [comment]
Changing WM_HOME (and --user-data-dir argument) can be used to make nwjs use a temporary profile directory, but nwjs ignores them both. Possibly due to security reasons (process isolation)?

**Comment by jarmopi** [comment]
Fixed. fb138bb500abc3f66684c44bd4ef3bb792604841, 0393a08effafb268b27462c58676e3031b2679fb.
