### ISSUE TITLE
Turn off gdm screen idle delay in bigtouch

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#162]
By default the screen turns black when no user inactivity has been detected in 15s. This is irritating especially with the bigtouch use case.

Curerntly there are no gdm dconf settings in the system but I tested making some by creating a dconf profile for gdm
`nano /etc/dconf/profile/gdm `

Added basic information
```
user-db:user
system-db:gdm
file-db:/usr/share/gdm/greeter-dconf-defaults
```

`nano /etc/dconf/db/gdm.d/profile`

And tested with following (random) settings
```
[org/gnome/login-screen]
banner-message-enable=true
banner-message-text='Type the banner message here'

[org/gnome/desktop/interface]
text-scaling-factor='2'

[org/gnome/login-screen]
logo='/usr/share/backgrounds/puavo-art/puavo-os_logo-white.svg'

[org/gnome/desktop/session]
idle-delay=uint32 300
```
`dconf update`

They worked ok... except the `idle-delay` setting :(

**Comment by juhaerk** [comment]
Cannot reproduce with latest image.  If problem persists, re-open this ticket.

**Comment by asokero** [comment]
Well the setting seems to have changed to a bit longer. Just wait for a couple of minutes. On bigtouch idle-delay is not needed.
