### ISSUE TITLE
Add information about: device type, device hostname, system version to login screen

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#179]

**Comment by asokero** [comment]
This could be developed as a gnome-shell extension.

**Comment by jarmopi** [comment]
Partially fixed by 8eda2659cd3a2107a89a32070e7d5dfdfa7462d9, d00615771d4f7b29b7096f70987cdab3023efbc0 and 68d37ab0fd39ff219b398b1ab1814ecb244373bb. Requires more work.

**Comment by jarmopi** [comment]
Fully fixed by 0e0d05f80a928358001adf3fbd2b6543bb2e5662, 9f3a77b94105a9cf56d00044b18be39735d07b09 and f92b89d5fa20f6f94e4b5e1bc419e850ba2dc7f9. Closing.
