### ISSUE TITLE
Swap partition not activated after update from Trusty to Dedian

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#185]
Only zram available.

`root@opinsys-kan-antti:/home/asokero$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3579        2250         145         303        1183         787
Swap:          1789          15        1773
`
`root@opinsys-kan-antti:/home/asokero$ swapon
NAME       TYPE        SIZE USED PRIO
/dev/zram0 partition 447,4M 3,9M    5
/dev/zram1 partition 447,4M 3,9M    5
/dev/zram2 partition 447,4M 3,9M    5
/dev/zram3 partition 447,4M 3,9M    5
`

Partitions
`root@opinsys-kan-antti:/home/asokero$ sudo fdisk -l
Disk /dev/sda: 117,4 GiB, 126035288064 bytes, 246162672 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x09789549

Device     Boot Start       End   Sectors   Size Id Type
/dev/sda1  *     2048 246162671 246160624 117,4G 8e Linux LVM

Disk /dev/mapper/puavo-swap: 4 GiB, 4294967296 bytes, 8388608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/puavo-tmp: 6 GiB, 6442450944 bytes, 12582912 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/puavo-images: 40 GiB, 42949672960 bytes, 83886080 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/puavo-state: 4 GiB, 4294967296 bytes, 8388608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/puavo-imageoverlays: 2 GiB, 2147483648 bytes, 4194304 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/puavo-home: 61,4 GiB, 65900904448 bytes, 128712704 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop0: 8,1 GiB, 8674050048 bytes, 16941504 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/zram0: 447,4 MiB, 469139456 bytes, 114536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/zram1: 447,4 MiB, 469139456 bytes, 114536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/zram2: 447,4 MiB, 469139456 bytes, 114536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/zram3: 447,4 MiB, 469139456 bytes, 114536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes`

Activating the swap partition fails.

`root@opinsys-kan-antti:/home/asokero$ swapon /dev/mapper/puavo-swap 
swapon: /dev/mapper/puavo-swap: read swap header failed`

After formatting the swap partition it can be mounted again.

`root@opinsys-kan-antti:/home/asokero$ mkswap /dev/mapper/puavo-swap 
Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
no label, UUID=1463bd18-076e-4004-93bd-d7a106881541`

`root@opinsys-kan-antti:/home/asokero$ swapon /dev/mapper/puavo-swap 
opinsys-os-opinsysrestricted-stretch-2017-03-21-053147-amd64 (laptop)
`

`root@opinsys-kan-antti:/home/asokero$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3579        2253         148         296        1177         792
Swap:          5885          15        5869
`

**Comment by juhaerk** [comment]
Fixed in 7f02c65f054993919613e536c2a96172fed2b0e4.
