### ISSUE TITLE
Opening change background settings window is too slow

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#190]
When opened for the first time it takes too long especially on a bit slower but still "modern" computer. It almost feels like the computer crashes. Could it have anykind of pre-built cache or such to make it faster.

**Comment by jarmopi** [comment]
Fixed by 2b3b88879613cb141fbd8cef4bf28dc73442bbbe, bb6a7ccf78482b08962447f905a348b305962145, 64beaeb159c94b6e930fbfa2ab96f7fdd82cf56b, be19801da6c052abb2ea10342baeabd5a1e929de and 9074772f09135d1eb75065cc807ae8bf711237aa.
