### ISSUE TITLE
Flash content does not work on any browser

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#191]
This is most likely a profile issue.

**Comment by asokero** [comment]
I have had this on two different profiles, but haven´t yet made effort to fond a way to reproduce it. The other one of the computers had only been used with the Stretch system.

**Comment by juhaerk** [comment]
Old ticket, has not been relevant a long time.

**Comment by basilstotz** [comment]
Hi,
I still have this issue on stretch: On guest accounts or on accounts which have been never used under trusty there is no flash content on chrom(e/ium). Firefox works.

On account which where used under trusty flash works on chrom(e/ium)!

Once I could activate flash by playing around with all kins of chrome settings. But I can not reproduce it!
