### ISSUE TITLE
Logout on a laptop occationally activates screenlock and ignores idle-delay settings

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#196]
After logout there are following problems
- Logout might take a while
- Screen gets black very quickly after logout 
- Sometimes the lock screen is displayed which is confusing 
- If lock screen is present you can´t get past it using the keyboard (esc etc.) only by draagging up with the mouse
- The idle-delay settings seems to be ignored and the screen goes blank in 15 seconds

**Comment by juhaerk** [comment]
Fixed in this commit: https://github.com/puavo-org/puavo-os/commit/f9ea7890a87dd89b28c0e659ea19e0b39b79859c
