### ISSUE TITLE
GDM login dialog is displayed only on one monitor

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#198]
This is a problem with teachers computers / classroom setups if computer is connected to a document camera or a video projector. In some cases the login screen ends up to the projector which might be shutdown and the user gets totally lost.

In Unity greeter login dialog follows the mouse.

**Comment by juhaerk** [comment]
This should be fixed now, as we setup monitors to clone mode since this commit: https://github.com/puavo-org/puavo-os/commit/f3bb26e85551a4bbb7a6c81d3e05849082c37c2b
