### ISSUE TITLE
Webmenu open to a wrong screen when used on a extended desktop with two screens 

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#217]
This problem came up when the behaviour was changed from Trusty version so that it won´t open according to the mouse cursor.

**Comment by jarmopi** [comment]
Fixed by 1575b6f7ec38082a27a66dbbae9211df4bdcdb8b, 3c887ee29d6c28c669b6a09da21f983eccb04187 and b88cbabd2296012d526557f26a3c5ec13504124d. Hopefully.
