### ISSUE TITLE
Add appinventor

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#224]
Same as here: https://github.com/opinsys/puavo/issues/318

**Comment by jarmopi** [comment]
4aa05a20d363a85319a821ac4d8d736b3547f826, 81859aa714e98b4dc46b725d8fefebd885524938, and 76dacd2b81e6cb02205ecd0d55f68d282b626e6a.

Plus 41e7052c539c010edef9dedbe14c4eee023c7e7a to actually make the thing work.
