### ISSUE TITLE
Unactive items in top left window menu look unclear

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#245]
Font colour needs to be changed in the gtk theme.

**Comment by jarmopi** [comment]
The relevant CSS declaration is in (GNOME's source code) data/theme/gnome-shell.css, selector `.popup-menu .popup-menu-item:insensitive`. The default color is almost white, but changing it to #808080, for example, is better. You need the `!important` override.

The real questions here are:
1) Why it is almost white by default?
2) Why modifying the Minwaita theme does not change the colors, why do you have to edit GNOME's source?
