### ISSUE TITLE
Add shortcut to sound settings from the panel volume menu

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#250]
It should be easier to access the sound settings (@gnome-control-center) menu from the gnome-panel. This could be done as a gnome extension to work the same way as in the old gnome flashback desktop.

**Comment by jarmopi** [comment]
Fixed in d80768e5707d5fe67cdfc407d784108978d03f78, f3fc8ebeb152717c7eeb32ba15ab807ee8af8fef and 3b2f998e080f1ca5f05ee0f2afdf841e29e7151d.
