### ISSUE TITLE
Change the direction of the arrows at the desktop panel 

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#251]
Originally the gnome-shell panel is located at the top of the screen. Therefore the arrows (for example keyboard layout) are also pointing down. As we have the panel at the bottom and the menus open upwards, the arrows should also point to that direction.

**Comment by jarmopi** [comment]
Commits b8fef513e31d9330b6ff460ce21dbb8f3218879a, a0c3fe1df04b02aa5152fd57f5790b618da0fd31, fdb2381b28aa3e1416ca8438e4b9c94391d3a586.
