### ISSUE TITLE
Printing is broken in Debian laptop installations

### ISSUE THREAD

**Issue by jarmopi** [puavo-org/puavo-os#254]
Debians installed on laptops don't see any printers, so printing cannot be done.

Debian fatclients seem to work.

**Comment by asokero** [comment]
Cannot reproduce this. Maybe laptop was connected to network/bootserver that does not have network printers?

**Comment by asokero** [comment]
Seems like this problem actually does happen occationally. For some reason sometimes printers were available. It should now be fixed https://github.com/puavo-org/puavo-os/commit/215bd88eafd9f59338095e1da1afc0eb6a9376d6
