### ISSUE TITLE
Gnome-shell ui does not react to mouse events with nvidia 304 drivers

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#263]
Based on experiences with two separate computers and GPUs, it seems that some of the gnome-shell ui elements do not work when using nvidia 304 drivers. Elements such as the bottom panel and the icon in it are normally visible but do not react when hovered or clicked. Also windows elements such as titlebar cannot be interacted with mouse. Applications (such as firefox) still seem to work normally.

**Comment by asokero** [comment]
- This issue sounds very similar: https://devtalk.nvidia.com/default/topic/894860/fedora-23-xorg-downgraded-nvidia-304xx-driver-gnome-shell-not-working/
- This one also https://ask.fedoraproject.org/en/question/77996/fedora-23-nvidia-gnome-shell-mouse-not-working/?answer=78031#post-id-78031

**Comment by Mazhoon** [comment]
Probably works nowadays.
