### ISSUE TITLE
Samba mounts never appear on laptops after offline login

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#269]
How to repeat with a newly installed laptop:
- Connect the laptop to bootserver network and login
- Check that the samba mount are available
- Reboot
- When back at login screen, make sure that the device is not connected to network
- Login using the same username
- After login connect the laptop to bootserver network -> Samba mounts won´t become available

**Comment by juhaerk** [comment]
Fixed on recent changes to `parts/sharedir/client/puavo-remotemounts-helper`.
