### ISSUE TITLE
"Ampère" is misspelled on the changelog page

### ISSUE THREAD

**Issue by jarmopi** [puavo-org/puavo-os#273]
The changelog page for Debian misspells "Ampère" as "Ampére".

https://fi.wikipedia.org/wiki/Andr%C3%A9-Marie_Amp%C3%A8re

**Comment by asokero** [comment]
Only Opinsys-os currently has releases and changelog so this issue is not relevant in this puavo-os repository. This has been fixed and the typo will be fixed when the changelog is ready and version released.
