### ISSUE TITLE
Constant cpu load on HP Folio 9470m

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#280]

**Comment by asokero** [comment]
Seems like shutting donw orientation sensors help lowering the load
`systemctl stop iio-sensor-proxy.service`

**Comment by juhaerk** [comment]
This affects load average only (?). The process is opening an input device ("/dev/input/event17" in one particular host), and opening it takes maybe something between 0.5 - 1 seconds.  The process periodically does "poll() + open() + 3 * ioctl() + close()" loop. Unless some effect is proven to affect battery life or user experience, not doing anything. Closing.
