### ISSUE TITLE
HP Stream 11 G3 won´t suspend on lid close

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#290]
Closing the lid only turns off the display and when opening the radios go to airplane mode. Repeating close/open the airplane mode goes of.

It seems like the computer thinks it is docked. Adding next setting to /etc/systemd/logind.conf and restarting  logind seems to enable the suspend.

edit file /etc/systemd/logind.conf and add
`HandleLidSwitchDocked=suspend`
Then...
`#systemctl restart systemd-logind.service`

**Comment by juhaerk** [comment]
Fixed in https://github.com/puavo-org/puavo-os/commit/ceccf874a977384254d28861265c5110b28ad679 plus https://github.com/puavo-org/puavo-os/commit/5029cbb73ccbc3d2e738729a337e18c2e2941df7
