### ISSUE TITLE
GDM user list is empty and confusing on personally administered devices

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#306]
If nobody has logged in to a device and it is set as a personally administered, user list is empty and looks broken. In such case a login text field should be active.

**Comment by juhaerk** [comment]
Fixed on recent commits: https://github.com/puavo-org/puavo-os/commit/4015c14d4f553ed8b5cbcaa9d52a5cf153a60ed4, https://github.com/puavo-org/puavo-os/commit/72aa5f8c0fb1a13fd79ce23fcc4eb9c6ac4acc86, 
https://github.com/puavo-org/puavo-os/commit/7a48cac919b0cf2f82ea594a9edec685bc4f669c and
https://github.com/puavo-org/puavo-os/commit/73c2524ff51c6478f51b8cecd440d62eda90158b.
