### ISSUE TITLE
Google Earth is missing an icon in panel when running

### ISSUE THREAD

**Issue by juhaerk** [puavo-org/puavo-os#314]

**Comment by jarmopi** [comment]
Strange. The .desktop file for GE is looking for an icon named "google-earth-pro", but all the icons in /usr/share/icons are named just "google-earth" (they're links created by a puavo-pkg script). But even after renaming them the icon still does not work. Changing the icon directive in the .desktop file to point an icon file directly *still* does not work. I wonder what the program is looking for?

**Comment by Mazhoon** [comment]
Seems to work in bullseye.
