### ISSUE TITLE
Add VMware horizon client

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#339]
https://my.vmware.com/web/vmware/details?downloadGroup=CART18FQ4_LIN64_470&productId=578&rPId=20573#product_downloads

Commandline parameters for the installer
https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/4.6/linux-client-installation/GUID-A5A6332F-1DEC-4D77-BD6E-1362596A2E76.html

**Comment by asokero** [comment]
Running the software given an error right after installation
```
$ vmware-view
/usr/lib/vmware/view/bin/vmware-view: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```
This can be fixed by 

`/lib/x86_64-linux-gnu$ ln -sf libudev.so.1 libudev.so.0`

But perhaps there is a nicer way around this?

**Comment by juhaerk** [comment]
This should work now in `opinsys-os`, unfortunately the code is not in `puavo-os` due to installer difficulties.
