### ISSUE TITLE
Xinput calibration with puavo.xorg.inputs.hitachi.calibration puavo-conf does not seem to work

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#343]
It seems that the setting (made with puavo tags) can be found at /usr/share/X11/xorg.conf.d/. Executing xinput_calibration from the command line does not seem to anything that would affect the touchscreen calibration. The same setting on the same hardware does work on the old Ubuntu based device image.

**Comment by juhaerk** [comment]
Our problem is the same as here: https://wiki.archlinux.org/index.php/Talk:Calibrating_Touchscreen

Basically, the Xorg now uses libinput instead of evdev, and it has a different configuration method for calibration (libinput(4) manual page describes configuration option "CalibrationMatrix").

**Comment by juhaerk** [comment]
https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-libinput/+bug/1718533
