### ISSUE TITLE
Maybe update Openshot?

### ISSUE THREAD

**Issue by juhaerk** [puavo-org/puavo-os#350]
Version 1.4.3-1 is in Debian, the changelog entry is from Sun, 29 Sep 2012 20:00:00 +0100, and Openshot has not been updated since. Figure out why and try updating it...

**Comment by asokero** [comment]
Added puavo-pkg installer for openshot appimage version. We might use this as default in the future. https://github.com/puavo-org/puavo-os/commit/cfa9f216ac649acb01d9eb2ad2d96efb9934e8b4
