### ISSUE TITLE
Desktop panel is sometimes unresponsive

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#360]

**Comment by asokero** [comment]
This might be due to a bug for example in gnome-shell, which would be tricky to fix/update. One thing to test is updating the extension itself. There is a newer version available: https://micheleg.github.io/dash-to-dock/

**Comment by juhaerk** [comment]
This is likely fixed in ee1ede0da984c9b84580587925c843b9ebf1696c. Or maybe not... closing anyway.
