### ISSUE TITLE
Add puavo-pkg installer for Mimio Studio

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#366]
Seems like there is only 32bit packages available, hope they still work.
- international version: https://d283cy74rh9ut.cloudfront.net/mimio-studio_11.53-intl_i386.deb
- english only: https://d283cy74rh9ut.cloudfront.net/mimio-studio_11.53-en_i386.deb

**Comment by juhaerk** [comment]
11.53 runs into the same problem (getrootdev_linux() failing with a crash) that we had previously: https://github.com/opinsys/puavo/issues/2

It appears I can get the 11.30 version (that we had in Trusty) to work under Debian Stretch...

**Comment by asokero** [comment]
The old version seems to work. We need to see if we actually need the new one.
