### ISSUE TITLE
Open shutdown dialog when pressing power button

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#385]
In the current version of gnome-shell the old interactive mode is missing. It would be useful to get a dialog with (logout, shutdown, reboot...) instead of just the curren default setting (ssupend. It seems that gnome only supports do nothing, shutdown and suspend options.

https://askubuntu.com/questions/839445/change-power-button-action-comand-for-interactive-option-in-gnome-3-20

**Comment by asokero** [comment]
I tried setting the dconf as "do nothing" and creating a desktop shortcut to power button press as gnome-sessin-quit --power-off, but that does not seem to work.

**Comment by Mazhoon** [comment]
Current Bullseye opens shutdown / cancel dialog. Better, but not quite there.

**Comment by asokero** [comment]
Good enough.
