### ISSUE TITLE
Installing a new laptop fails

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#389]
PXE installing a laptop fails in the end of the installation while adding adm-users from puavo.

**Comment by basilstotz** [comment]
I had the same issue (but could be "solved" by not accepting the new adm-users) while updating bootservers to v58. 

Is this bootserver issue also solved with  https://github.com/puavo-org/puavo-os/commit/ccdedb2953c8da78598348c3ee135522713850a5 ?
