### ISSUE TITLE
smbd does not start on first reboot after bootserver installation

### ISSUE THREAD

**Issue by juhaerk** [puavo-org/puavo-os#400]
`smbd`does not start on first reboot after bootserver installation, but on subsequent boots it does.

**Comment by basilstotz** [comment]
same issue with nbd-server

**Comment by juhaerk** [comment]
Really? I think I have fixed this regarding smbd a long time ago. Not seen this with nbd-server either...

I do not know should I close this or not... closing ;-)  Re-open if there is an issue with smbd, create a new issue if there is a problem with nbd-server.
