### ISSUE TITLE
Option to activate Password change recommended -message for old passwords after login

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#403]
So organizations need a way to encourage users to change their passwords if they are too old. At first only a recommendation for password change is needed. Feature could be something like
- Message after login about old password with a button pointing to open password change tool
- Puavo-conf to activate/deactivate the feature and to change the change interval

**Comment by juhaerk** [comment]
Fixed by 2b900d34961c8d2a768e6425ed15035796e9948d and and https://github.com/opinsys/puavo-users/commit/72316b3bf965470e155b26657fe1cd3098287f1d.
