### ISSUE TITLE
Bootserver hostnames should be limited to 15 characters or less due to Samba

### ISSUE THREAD

**Issue by juhaerk** [puavo-org/puavo-os#421]
/etc/samba/smb.conf might have an unsupportedly long "netbios name", because the puavo hostname is copied there and we allow longer hostnames in Puavo.  This results in constant "cannot find server" error messages from nmbd.

See https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and

We should perhaps validate (in Puavo) that bootserver hostnames are not 16 or more during bootserver registration.

**Comment by Mazhoon** [comment]
Nowadays hostname goes to `server string` (plenty of 15+ char bootserver hostnames in use without issues), `netbios name` seems to be the same as `workgroup` in each of the instances I checked
