### ISSUE TITLE
gnome-mines hangs quite often while playing the game

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#438]
This seems to happen with different hardware after playing the game for a little while.

**Comment by ralf-krause** [comment]
I found this also in Puavo from 2019-03-12.

**Comment by asokero** [comment]
The actual problem might have been in the way puavomenu desktop component launches the applications. This has now been fixed: https://github.com/puavo-org/puavo-os/commit/9f430461d8863488ca6d8b8dbb98a0490fb02dce

After a small gaming session I was unable to reproduce this problem with the latest test version, but it might need more testing to be sure. Still it looks promising. This fix will be in the next production image and will probably fix some other weird issues and crashes.

**Comment by juhaerk** [comment]
To explain why the change is relevant... it is due to the way program stdout/stderr was (not) handled. Thus, if a program that is launched from puavomenu is writing lots to stdout/stderr, it could hang later.
