### ISSUE TITLE
Add drivers for the promethean activboards

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#440]
It seems that after doing these steps on a live/overlay system the board works:

This discussion was used as a reference https://support.prometheanworld.com/article/?kb=1623
```
sudo apt-get install libqt5webenginewidgets5
sudo mv /usr/share/promethean/lib /usr/share/promethean/lib.pois
sudo ln -s /usr/lib/x86_64-linux-gnu/ /usr/share/promethean/lib
```
Create `/usr/share/X11/xorg.conf.d/75-promethean.conf`
```
Section "InputClass"
        Identifier   "calibration"
        MatchProduct "Promethean Limited ACTIVboard"
        Driver       "evdev"
EndSection
```
There might be some better way to handle the lib issues (linking made above). Perhaps by editing  `/etc/xdg/autostart/activmgr.desktop` and/or `/usr/local/bin/activmgr.sh`.

**Comment by juhaerk** [comment]
This should work now, I think, but I have not tested with an actual device: https://github.com/puavo-org/puavo-os/commit/1bc7cd71ef19ec1e3c07e95742bbf6bfd05a93a2

**Comment by juhaerk** [comment]
Oh, only custom installations on laptops are supported for now. And those perhaps need to be reconfigured manually once the new puavo-pkg changes (puavo-conf integration, fatclient support, ...) come in.
