### ISSUE TITLE
LoggerPro crashes when pressing linear fit toolbar button

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#444]
Seems to be fixed by using the trysty library 
https://packages.ubuntu.com/trusty/amd64/libgtkmm-2.4-1c2a/download libgdkmm-2.4.so.1

**Comment by juhaerk** [comment]
Fixed: https://github.com/puavo-org/puavo-os/commit/b44ef82557ffd0e9973d73d72acedba280997bc7
