### ISSUE TITLE
Google Earth crashes when searching a location

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#445]
The Puavo client is running in guest mode. Please start Google Earth and close the stupid tip popup. Then write your favourite location into the upper left text field, e.g. Berlin. Click on the button "Search" now. Google Earth crashes immediately.  :-(

Puavo opinsys-os-opinsy-stretch-2019-01-15-094627-amd64

**Comment by asokero** [comment]
Thanks for the issue. I can repeat this and this also seems to be an issue also upstream on some systems. https://productforums.google.com/forum/#!msg/maps/ZeedmdEIUPw/3frKyD7uAwAJ

This is probably some library issue that we need to sort out.

**Comment by asokero** [comment]
Just note to self.Tried downgrading the google earth to version v7.3.0.3832. It does not crash, but the search in this version does not work properly anymore. It always goes to "null" coordinates.

https://www.google.fi/intl/fi_ALL/earth/versions/#download-pro

**Comment by juhaerk** [comment]
The exact same version of Google Earth on Buster does not crash. On Stretch it does.

**Comment by asokero** [comment]
This seems to be an upstream bug with Google Earth that never gets fixed. This should be a work around for it https://github.com/puavo-org/puavo-os-pkg/commit/749597df8a60b3399b56581c62dbbcc7e4b54163
