### ISSUE TITLE
Firefox does not start with the school site

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#446]
The Puavo client is running in guest mode. Please start Firefox and you will get two browser tabs. The first tab shows an advertising "Firefox für unterwegs" and in the second tab a "Firefox Privacy Notice". When I quit the application and open Firefox for the second time then I get the web site of the school.

**Comment by juhaerk** [comment]
Thanks, I have seen this as well. For new Firefox profiles this occurs, and unfortunately with guest profile each session is with a new profile.

I have a feeling this is a regression that happened with some Firefox update... I first noticed this early this year, but it may have been there longer.
