### ISSUE TITLE
Shorten the german menu "Interaktive Tafeln"

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#447]
The Puavo menu shows "Interaktive Wandtafeln" in two lines. I think we should get a shorter text. Nobody uses "Interaktive Wandtafeln" ... we say "Interaktive Whiteboards" or "Interaktive Tafeln". Please use "Interaktive Tafeln" in the Puavo menu.

**Comment by juhaerk** [comment]
Fixed by basilstotz: https://github.com/puavo-org/puavo-os/commit/5fa168506ef5333e361bbe1c25f27a502e8f15a7
