### ISSUE TITLE
Laptop screen brightness is always 100% after reboot

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#455]
This easily drains the battery without the user noticing it.

Could we have 
- any change to save the current setting as default for that device so it would be remembered over reboot?
- puavo-conf to set default screen brightness
- hardware tweak for device specific default

**Comment by asokero** [comment]
A note: when using image overlay the brightness persists over reboot.

**Comment by asokero** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-backlight@.service.html

**Comment by juhaerk** [comment]
Fixed in https://github.com/puavo-org/puavo-os/commit/38dd6de5ebd7047edb4ae159d5d95547599f19f1.
