### ISSUE TITLE
Gimp is unstable

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#457]
There has been several user reports that Gimp is unstable. Currently there is no clear way to repeat the problem.

**Comment by juhaerk** [comment]
I can not reproduce either.

Could it be a memory problem? On hosts with two gigabytes of memory, if some web browser tabs are open plus there is active work happening in gimp, maybe memory runs out?

**Comment by juhaerk** [comment]
We have a theory that the problem might occur only when started from puavomenu, and it could be a puavomenu-issue (not reading stdout/stderr from gimp, and gimp hanging).

Closing ticket. Re-open if the issue persists when tested with the latest puavomenu fixes.
