### ISSUE TITLE
Bootserver downgrade from Buster to Stretch messes up ldap

### ISSUE THREAD

**Issue by juhaerk** [puavo-org/puavo-os#462]
This problem is far to the future and which we may not even need to resolve, but anyway:

Downgrading bootserver from Buster to Stretch results in a system that does not boot.  "setup_samba" script hangs on "slapcat -H", because downgrading ldap database it not possible. Automatic recovery of the ldap database is not successful.

**Comment by asokero** [comment]
Buster and Stretch are long gone.....
