### ISSUE TITLE
Puavo should show emoticons

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#464]
Hi,
I found that Puavo does not show emotions. Kids are using emoticons on their smartphones and emoticons are very important in their communications. So Puavo also should come with emoticons.
The first screenshot shows the missing emoticons in Puavo, the second shows the same web site in Android and the third with iOS.
Best regards, Ralf
![emoticons-puavo](https://user-images.githubusercontent.com/27956839/55983888-70490d00-5c9c-11e9-9ccc-53deda224a62.png)
![emoticons-android](https://user-images.githubusercontent.com/27956839/55983976-ad150400-5c9c-11e9-8505-afd326341472.png)
![emoticons-ios](https://user-images.githubusercontent.com/27956839/55983990-b43c1200-5c9c-11e9-98c0-8630b7a61f13.png)

**Comment by ralf-krause** [comment]
I forgot ... I found this in Puavo from 2019-03-12.

**Comment by juhaerk** [comment]
I tested this quickly with Firefox, Chromium and Chrome. Works on Firefox, not on Chrom* browsers.

**Comment by ralf-krause** [comment]
Unfortunately this problem is not solved yet. The problem exists in Puavo Buster and Puavo Bullseye, too. 

There are a lot of web platforms using emoticons on their page. A lot of schools are using Moodle. The new Moodle version 4.0 is greeting the logged in user with a string on the frontpage. Yes, you could say that the students should take the Firefox browser to show the emoticons. The first screenshot shows the Magdeburg Bildungsportal 4.0 with Chrome, Chomium and with the new browser "Gnome Web". The second screenshot shows the correct emoticon. The third screenshot shows the same page on an ipad.

The main users of Puavo are teachers and students ... and they like to use emoticons. When we show Puavo as a tool for everyone it must work for everyone and it should show all website content in every browser. Otherwise the small emoticons on the website, in a chat or in a forum could be an argument against devices with Puavo. We need the best user experience really with all programs. 

![moodle40-chrome](https://user-images.githubusercontent.com/27956839/193259333-8a3f4e59-c35a-4cf5-b2e9-72805f601759.png)

![moodle40-firefox](https://user-images.githubusercontent.com/27956839/193262249-934857e1-43c7-4079-be4d-5d827dae8781.png)

![16EE413C-ED7B-469C-82C2-AC341398977A](https://user-images.githubusercontent.com/27956839/193262566-41aa0872-b36e-4abc-a563-514ad968a83a.jpeg)

**Comment by Mazhoon** [comment]
Thank you for your feedback, should be fixed in next Bullseye image: https://github.com/puavo-org/puavo-os/commit/99a4f632a52c3996406c14f5a058b216b95bfa5f
