### ISSUE TITLE
FileZilla should be integrated

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#465]
I 'm using a lot of server connections with FileZilla on other computers. Puavo does not come with FileZilla. I can't say if gFTP comes with all secure file protocols. I found that I could not connect ftpes:// to a server which is important for my work.
Ralf

**Comment by basilstotz** [comment]
https://gitlab.gnome.org/GNOME/gvfs/issues/4 :

"Hmm, it is the first time I heard about "ftpes", but it seems that this is the well-known term. However, it seems that implicit TLS is not defined in RFC and is recommended to not be used by new implementations. Thus I am in doubts that it is a good idea to adding this. However, if you willing to provide merge request for it, I won't refuse it..."
