### ISSUE TITLE
Puavo-pkg installer for Minecraft

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#468]
https://www.minecraft.net/fi-fi/download/alternative/

**Comment by basilstotz** [comment]
Maybe also consider to include minetest (and some mods ), a free variant of minecraft

https://packages.debian.org/de/stretch/minetest

(6 MByte installed)

I

**Comment by asokero** [comment]
Hi,

Minetest is already in the basic image (not in the menu though).
