### ISSUE TITLE
Running puavo-update-airprint-ddns at bootserver cron does not work?

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#474]

**Comment by basilstotz** [comment]
It seems that other cronjobs are not running too (on the same bootserver):

- Munin is not compiling data at all. The graphs are empty
-  user@box$ puavo-bootserver-last-user-sessions 
         grep: /var/log/kdc.log: Datei oder Verzeichnis nicht gefunden (-->file not found)
    user@box$
  just gives an error!

**Comment by juhaerk** [comment]
Fixed in https://github.com/puavo-org/puavo-os/commit/73a6d1d710a5da75cc03abc193e513666ba19a0f.

The other two issues mentioned by Basil are real, but unrelated.
