### ISSUE TITLE
Etcher asks for superuser password

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#477]
I want to copy sd cards with Puavo.

Etcher is a very simple and useful app that can be downloaded as a portable AppImage. You can put it anywhere in your personal folder or on the desktop. The app starts with a double click. You choose the sd image to be copied. And you choose the sd card in the card slot of your Puavo laptop. You start the sd flashing with the right button "Flash". 

No, the flashing does not start because you need to have the superuser password.

![etcher-needs-superuser-password](https://user-images.githubusercontent.com/27956839/59017081-00da3e80-8843-11e9-9466-09fa06dd4677.png)

**Comment by asokero** [comment]
Currently normal users do not have rights directly on mass storage devices, only partitions mounted by the user (such as formatted usb stick). This is a security feature on a shared laptops. To be able to use such applications as etcher or dd or to set a root password you will need to have...
a) a laptop that is set as personally administered from the device settings at puavo web
b) be the primary user on that device

If the previous requirements are met you can set a temporary root password by...
1) login as the primary user of the laptop
2) open the terminal application
3) type sudo passwd
4) set your temporary root password

After this you can launch Etcher etc. and use the previously set password.

**Comment by basilstotz** [comment]
I Just posted the same workaround an hour ago.

**Comment by asokero** [comment]
Closing this issue as there is a workaround and it is basically a duplicate to older issue #341.
