### ISSUE TITLE
Add puavo-pkg installer for thymio suite

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#483]
https://www.thymio.org/thymio-suite/

**Comment by basilstotz** [comment]
Did a a quick try and stuck here:

adm-xxxx@laptop:~$ LC_ALL=C sudo flatpak install flathub org.kde.Platform/x86_64/5.12 --user
Installing: org.kde.Platform/x86_64/5.12 from flathub

error: While pulling runtime/org.kde.Platform/x86_64/5.12 from remote flathub: Unable to set xattr: Operation not supported
adm-xxxx@laptop:~$

**Comment by basilstotz** [comment]
https://packages.debian.org/buster/aseba !

**Comment by asokero** [comment]
Aseba was added to the last months image so closing this one.
