### ISSUE TITLE
Add launcher for Vernier Data Analysis

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#490]
https://chrome.google.com/webstore/detail/vernier-graphical-analysi/dncgedbnidfkppmdgfgidcepclnokpkb

**Comment by juhaerk** [comment]
Maybe works, maybe does not... unclear why. Perhaps with a Google Chrome profile created with the latest Chrome version it does not work?  Error message is: "Native Client Startup Error / Service Loading: dc-rpc".

**Comment by asokero** [comment]
This can be preinstalled via chrome puavo-conf policies.
