### ISSUE TITLE
Filezilla should be updated 

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#492]
Hi,
the current Puavo comes with an old Filezilla 3.24.0. Please update to Filezilla 3.45.1. 
Ralf

**Comment by asokero** [comment]
Filezilla version is currently defined by Debian 9 Stretch as basically are all the applications. It will be updated when Puavo is updated to the next Debian version which is Buster. This will happen during 2019. 
Unless there is a certain functionality missing, the applications will not be separated from the Debian versions.

**Comment by Mazhoon** [comment]
Has been updated with Buster, and Bullseye.
