### ISSUE TITLE
Scratch 3.0

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#493]
The offline version die Scratch 3.0 is ready. Please install the offline version because there are a lot of schools without any wifi. Currently the Puavo menu shows a web link to the online version.

**Comment by asokero** [comment]
It seems there is no upstream linux package available from Scratch 3.0, only Windows and Mac.

https://scratch.mit.edu/download
"When will you have Scratch Desktop for Linux?
Scratch Desktop on Linux is currently not supported. We are working with partners and the open-source community to determine if there is a way we can support Linux in the future. Stay tuned!"

Needs more research how to make it work offline.

**Comment by ralf-krause** [comment]
Hi Annti,
I installed Scratch 3.0 in a Raspberry Pi. So there is a version for Linux because Raspbian is Debian Duster. 
Ralf

**Comment by Mazhoon** [comment]
Scratux ("Scratux is an offline version of Scratch 3.0 for Linux.") has been available as a Puavo-pkg since https://github.com/puavo-org/puavo-os-pkg/commit/679a77698fbe97f0f2e7e3616d340d927eb1773e
