### ISSUE TITLE
Move FileZilla to the Internet menu

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#497]
Hi,
in the new Puavo image I found FileZilla in the Tools menu. FileZilla is a program which is used to copy files to internet servers or network servers. Therefor the program should be found in the Internet menu. With the same argument the program gFTP should be deleted from the Tools menu.
Ralf

**Comment by asokero** [comment]
Filezilla added to the internet menu. 78284df01956fc1ee4c4db247327b4a34cff0280
