### ISSUE TITLE
USB stickfactory changing between two images

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#499]
Stick factory has a following problem
- Write image A (for example KOE) to usb sticks
- Change the image to image B (f. ex. KTP) to be written before the writing finishes

In such case writing the image A continues to be written as planned, but the final verification is done in comparison to image B. This results a failed verification and immediate start of writing the image B over the just finished job. In such case writing image A should be verified as image A and complete as such.

**Comment by juhaerk** [comment]
I think this should work now.
