### ISSUE TITLE
Change panel opacity when windows get close to panel

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#508]
This makes UI less confusing when windows go close or under the desktop panel. 

dash to panel extension dconf:
```
trans-use-custom-opacity=true
trans-use-dynamic-opacity=true
trans-dynamic-anim-target=0.95
```

**Comment by juhaerk** [comment]
Great work, Antti! ;-) https://github.com/puavo-org/puavo-os/commit/8728aec32e308916970bff7d8c740ad080fbfb32
