### ISSUE TITLE
Missing apps from Buster

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#509]
- [x] ashforge
- [x] Mypaint
- [x] pinta
- [x] FIrefox
- [x] epiphany
- [x] zoom
- [x] teddy bear programming
- [x] eclipse
- [x] pycharm
- [x] nightcode
- [x] Ekapeli-alku
- [x] old Ekapeli (Java)
- [x] Celestia
- [x] cmaptools
- [x] TI CAS
- [x] fmit
- [x] virtualbox

**Comment by juhaerk** [comment]
There is no "pinta" package in Buster, do we still need it?

**Comment by juhaerk** [comment]
The problem with "mypaint" is that in Buster it conflicts with Gimp: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897909

**Comment by juhaerk** [comment]
"celestia" disappeared after Jessie, and on Stretch we used the package from Jessie. I would not want to add packages from Jessie anymore, any ideas on what we should do? Go puavo-pkg if possible?

**Comment by juhaerk** [comment]
Nightcode can be optionally installed with a puavo-pkg and it works, it is just not installed by default because it takes quite a bit of space and is used only by a few.

**Comment by juhaerk** [comment]
Zoom also can be installed optionally with a puavo-pkg package.

**Comment by juhaerk** [comment]
I presumed "ashforge" means "flashforge".  Works for me with no changes.

**Comment by juhaerk** [comment]
"cmaptools" just shuts down (with success code) after splash screen.

**Comment by juhaerk** [comment]
TI CAS should work just like in Stretch, it just is not installed by default.

**Comment by juhaerk** [comment]
"Pycharm" works, just not installed by default.

**Comment by juhaerk** [comment]
"Eclipse" was removed from Buster. Maybe creating a puavo-pkg from https://www.eclipse.org/downloads/packages/ might be a good idea?

**Comment by juhaerk** [comment]
"fmit" was removed from Buster. "unstable" has new packages, though, and I suppose it is still among the best free software tuners out there...

**Comment by juhaerk** [comment]
"Teddy bear programming" also works, it is just not installed by default.

**Comment by juhaerk** [comment]
Fmit added to the build: https://github.com/puavo-org/puavo-os/commit/7be1c9fffd6ad057ac54500af68277f427e6fa1a

**Comment by juhaerk** [comment]
Celestia added as a puavo-pkg package: https://github.com/puavo-org/puavo-os/commit/8c1eb3caa6d643698212835a2be379904e568341

**Comment by juhaerk** [comment]
The situation with Virtualbox is tricky: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794466

**Comment by juhaerk** [comment]
Virtualbox taken from virtualbox.org Buster packages (a new apt source added).

**Comment by juhaerk** [comment]
Icedtea javaws appears to be okay with the old Ekapeli.

**Comment by juhaerk** [comment]
All done, closing ticket! Make a new one in case something is missing!
