### ISSUE TITLE
Possible NFS problems on fatclient (buster)

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#513]

**Comment by juhaerk** [comment]
Not much news here... Buster kernel (4.19.67-2+deb10u2) is not as reliable as the Stretch kernel was regarding this. "flock" returns I/O error on NFS mount when it happens. Thus we can detect it when it happens. "nolock"-option in NFS mount options probably fixes it, but this has repercussions.

**Comment by juhaerk** [comment]
The commit da84bc4ff519197eae1b50ace0b3354561ceb624 referenced in https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.97 might be relevant. Though perhaps not. This kernel should eventually make its way to Buster, so we could wait or try the patch ourselves. I am personally testing a kernel from Buster-backports (currently 5.4.0-0.bpo.2-amd64) to see if there is any effect regarding this bug.

I did test vers=4.1 and vers=4.2 (NFS protocol version), version 4.2 hangs the system pretty fast, 4.1 is more stable but not close to 4.0 stability (that is good enough on 4.9.x kernels but not on 4.19.x).

**Comment by juhaerk** [comment]
After testing kernel 5.4.0-0.bpo.2-amd64 for two weeks now on one host (a bit less actually), the problem has not come up, but this testing is not adequate to say if the problem has been fixed there (this is promising, though). In any case I would like to get the fix to 4.19.x kernels, thus I am going to test the 4.19.98-1 kernel from proposed updates for now (package "linux-image-4.19.0-8-amd64").

We have problems reproducing this bug, it does not occur in our automatic stress testing hosts for some reason.

**Comment by juhaerk** [comment]
Kernel 4.19.98-1 does not fix the problem.
