### ISSUE TITLE
Add support for adding WPA2 Enterprice network settings to puavo

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#516]
Currently this is not possible. 

Here is one example from a working settings (with changed id/account/passwords), but this one does not require any certificate.

```
[connection]

id=ZZZZZZZZZZZZZ

uuid=c4714972-59c0-4cfa-97a1-59f9d5f7d3e3

type=wifi

permissions=


[wifi]

mac-address=64:80:99:BA:DC:1D

mac-address-blacklist=

mode=infrastructure

ssid=ZZZZZZZZZZZZZ


[wifi-security]

auth-alg=open

key-mgmt=wpa-eap


[802-1x]

eap=peap;

identity=xxxxxxxxx

password=yyyyyyyyyy

phase2-auth=mschapv2


[ipv4]

dns-search=

method=auto


[ipv6]

addr-gen-mode=stable-privacy

dns-search=

method=auto
```

Some networks also seem to require a certificate to be added:

https://www.jyu.fi/digipalvelut/fi/ohjeet/internet/wlan-linux

So in minimum it is needed to be possible to enter:
- ssid name
- username
- password
- certificate

**Comment by juhaerk** [comment]
We have added support in latest commits to EAP-TLS, EAP-TTLS and EAP-PEAP (with or without certificates, with optional password).
