### ISSUE TITLE
Gnome has some missing translations (finnish)

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#517]
- [ ] Aggregate menu - Network stuff, battery status
- [ ] Logout dialog
- [ ] Shutdown dialog
- [ ] Secondary click on desktop icon > Open With Other Application
- [ ] Login screen buttons (maybe not a translation issue)

**Comment by juhaerk** [comment]
This is an old problem that resurfaced after I updated the gnome-shell extensions we use.
See https://github.com/puavo-org/puavo-os/commit/73900488fca00541b50357eb73ef874d71c1ab9a
