### ISSUE TITLE
Make default login screen wallpaper configurable

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#539]

**Comment by juhaerk** [comment]
Well, it kind of is and has "always" been.

To use it: copy a picture file to /usr/share/backgrounds/puavo-greeter, for example "Yellowflower.jpg". Do:
```
sudo puavo-conf puavo.greeter.background.mode dynamic
sudo puavo-conf puavo.greeter.background.default Yellowflower.jpg
sudo /etc/puavo-conf/scripts/setup_loginscreen_background
```

What exactly should be fixed? Maybe it should be possible to use absolute paths in `puavo.greeter.background.default` ?

**Comment by juhaerk** [comment]
Actually the above does not work. The image should be under `/usr/share/backgrounds/puavo-greeter` and then all subdirectories must be included in the path, that is, "default/Mushrooms_3_by_moritzmhmk.jpg" is okay in our current image, but "Mushrooms_3_by_moritzmhmk.jpg" is not. After looking at our database contents it appears that this functionality has not been used after Ubuntu Trusty...
