### ISSUE TITLE
Ethernet does not work on Lenovo thinkpad 11e laptop

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#546]
Eth0 does not get active on this laptop with Realtek Semiconductor Co., Ltd. RTL8111/8168/8411. currently tested only on Stretch.

root@lk-lenovo-11e:/images$ lspci
00:00.0 Host bridge: Intel Corporation Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register (rev 0e)
00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
00:13.0 SATA controller: Intel Corporation Atom Processor E3800 Series SATA AHCI Controller (rev 0e)
00:14.0 USB controller: Intel Corporation Atom Processor Z36xxx/Z37xxx, Celeron N2000 Series USB xHCI (rev 0e)
00:1a.0 Encryption controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Trusted Execution Engine (rev 0e)
00:1b.0 Audio device: Intel Corporation Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller (rev 0e)
00:1c.0 PCI bridge: Intel Corporation Atom Processor E3800 Series PCI Express Root Port 1 (rev 0e)
00:1c.2 PCI bridge: Intel Corporation Atom Processor E3800 Series PCI Express Root Port 3 (rev 0e)
00:1c.3 PCI bridge: Intel Corporation Atom Processor E3800 Series PCI Express Root Port 4 (rev 0e)
00:1f.0 ISA bridge: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Power Control Unit (rev 0e)
00:1f.3 SMBus: Intel Corporation Atom Processor E3800 Series SMBus Controller (rev 0e)
04:00.0 Network controller: Intel Corporation Wireless 7260 (rev c3)
05:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)

**Comment by juhaerk** [comment]
Probably it tries to use r8169, but needs r8168 that does exist in the image, it just needs some modprobe tricks to work?

**Comment by asokero** [comment]
puavo.kernel.modules.load=r8169 seems to do the trick. Maybe hardware quirk with this setting might be possible?

**Comment by asokero** [comment]
Fixed in the latest images.
