### ISSUE TITLE
Add support for RTL8821CE?

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#570]
http://se.archive.ubuntu.com/ubuntu/pool/universe/r/rtl8821ce/rtl8821ce-dkms_5.5.2.1-0ubuntu3_all.deb ?

`02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter`

**Comment by asokero** [comment]
Installing the Ubuntu package to Buster device seems to work. And after reboot the wifi works.

`
sudo dpkg -i rtl8821ce-dkms_5.5.2.1-0ubuntu3_all.deb 
Selecting previously unselected package rtl8821ce-dkms.
(Reading database ... 764510 files and directories currently installed.)
Preparing to unpack rtl8821ce-dkms_5.5.2.1-0ubuntu3_all.deb ...
Unpacking rtl8821ce-dkms (5.5.2.1-0ubuntu3) ...
Setting up rtl8821ce-dkms (5.5.2.1-0ubuntu3) ...
Loading new rtl8821ce-5.5.2.1 DKMS files...
Building for 4.19.0-8-amd64 5.7.0-0.bpo.2-amd64
Building initial module for 4.19.0-8-amd64
Done.

rtl8821ce.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-8-amd64/updates/dkms/

depmod...

DKMS: install completed.
Building initial module for 5.7.0-0.bpo.2-amd64
Error! Bad return status for module build on kernel: 5.7.0-0.bpo.2-amd64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/5.5.2.1/build/make.log for more information.
dpkg: error processing package rtl8821ce-dkms (--install):
 installed rtl8821ce-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 rtl8821ce-dkms
`

**Comment by Mazhoon** [comment]
Works with recent kernel in Bullseye.
