### ISSUE TITLE
Users cannot remove print jobs from their own print queue

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#571]
Users cannot remove unfinished/failed jobs from their own print queue. This can be repeated for example on a laptop with a local usb/network printer.
- Add a new printer
- Make sure the printer is not available (so that the job stays in the queue)
- Print to the selected printer
- Go to Gnome System settings > devices > Printers > Printer
- Try to cancel the print

**Comment by juhaerk** [comment]
Fixed by this commit: https://github.com/puavo-org/puavo-os/commit/619a4734e964d3fc32d907d9ae6ff360c3866f02
