### ISSUE TITLE
Remote factory reset for mass of devices

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#588]
Currently factory-reset can be done locally on single device by `puavo-reset-laptop-to-factory-defaults` . To reset for example 200 devices is extremely troublesome.

Therefore it would be usefull to be able to set selected devices to factory reset mode from puavo-web device management. This function could have two modes:
1. kind and polite mode that sets the device to reset mode after it has received the setting. And after reboot it would as to verify that the device will now be erased.
2. force mode to set it for example on a stolen device.

**Comment by tuomasjjrasanen** [comment]
AFAIK, this is solved? @asokero

**Comment by asokero** [comment]
This is not perhaps feature complete, but good enough for now. For future feature let's open new issues.
