### ISSUE TITLE
Add puavo-pkg installer for thymio suite

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#604]
In issue https://github.com/puavo-org/puavo-os/issues/483 you added the old Aseba tool from early 2019.

Meanwhile we can get a new and very nice programming suite for the Thymio roboters.
https://www.thymio.org/products/programming-with-thymio-suite/
The Thymio Suite 2.3.x comes with some very useful programming tools. Teachers and students can choose their favourite tool from different programming languages: VPL, VPL3, Scratch, Blocky, Aseba, Python (coming soon) and ROS. To use Thymio roboters with the Thymio Suite on Puavo devices we would be very happy to get a new installer package with this Thymio Suite.

I installed the flatpak on my personal Puavo device and it works fine. https://www.thymio.org/linux-installation/ But installing the Thymio software manually on a set of Puavo devices in a school would be too difficult. Basil just made a installer package to test the installation with the current Puavo Bullseye image ... yes, it's nice.

I also installed the Thymio Suite on a computer with LinuxMint 21. There you can get the Thymio Suite in the 

Would you please think about a new installer package "Thymio Suite" for Puavo Bullseye? Daniela plans to bring a lot of Puavo roboters into the schools in Magdeburg. The Thymio can't be programmed with iPads or Android standalone. You always need to use the Puavo device or another notebook with Windows or macOS for this. The tablats need a relais station with the Thymio Suite.

**Comment by ralf-krause** [comment]
I forgot to send the screenshots from the Thymio Suite 2.3.0. 

The Puavo installation package comes from Basil and uses the Thymio Suite 2.3.0 (the current is 2.3.2). I installed it on my Puavo test device pool0002.einszueins.opinsys.fi. Daniela asks if she can buy some Thymio robots for the new Puavo schools in Magdeburg but she must know if they will get the software on their Puavo devices.

![thymio-1](https://user-images.githubusercontent.com/27956839/194529766-08078f38-4e0d-4051-afd3-5d1507e23681.png)

![thymio-2-scratch](https://user-images.githubusercontent.com/27956839/194529852-6df4c073-10df-4175-b3f7-675e4c32701f.png)

![thymio-3-blocky](https://user-images.githubusercontent.com/27956839/194529879-ec8986dc-bddc-4df2-8b09-0c2c92ec3386.png)

![thymio-4-vpl3](https://user-images.githubusercontent.com/27956839/194530218-6a29c5dc-c7e9-4695-8d93-321a2e3ce1fc.png)

![thymio-5-aseba-studio](https://user-images.githubusercontent.com/27956839/194530253-c5b8033a-5126-42d2-8105-25fd4de30cd7.png)

**Comment by ralf-krause** [comment]
For the installation of the Thymio Suite 2.3.2 I got help from Basil Stotz.

$ git clone https://[github.com/basilstotz/puavo-extra-pkg](http://github.com/basilstotz/puao-extra-pkg)
$ cd puavo-extra-pkg
$ make

With this process I could find a lot of additional packages in the folder /home/user/puavo-extra-pkg
Now I can install the Thymio Suite manually in Puavo developer mode. 
Therefore I must have sudo rights on the current Puavo device ... otherwise I can't install.

$ sudo apt update
$ sudo apt install flatpak
$ sudo puavo-pkg install puavo-extra-pkg/thymiosuite.tar.gz
$ thymiosuite

The last command line starts the Thymio Sute 2.3.2. I did all these things and now I have the Thymio Suite installed in the Puavo developer mode. Now I can reboot the Puavo device using the developer mode again. I can login with any user registrated for my school. My test device is md-lap-3011.magdeburg.opinsys.fi and my test users were lehrer.westring and schueler.westring. Both users could use the Thymio Suite. To get a start icon in the favorites I started the thymiosuite with the Terminal. With a right clickon the icon in the bottom line I could take the icon into the favorites. Clicking the icon the Thymio Suite starts without using the Terminal and typing thymiosuite.

This installation works for a few Puavo devices but not for more than one school in Magdeburg. Therefore it would be fine if we will get an addional Puavo package and a Puavo config parameter so we can install the Thymio Suite if it is needed. In other cases Puavo should not come with the Thymio Suite because it is using a lot of space on the device.

You also can delete the very old Aseba Studio from the Puavo image. The Aseba Studio is from 2018 ... it's very old and allows a rather old fashioned programming of the Thymio.The software is mark as unstable for Buster and Bullseye. Also it starts with an error message that somethin is not installed correctly (please look at my screenshot). The Thymio Suite is from 2022 and helps to program the Thymio with students in 3rd to 6th classes. The Thymio is open hardware.

I hope we will get the Thymio Suite package for Puavo.  :-)

Best regards from Germany
Ralf

![aseba-studio-error](https://user-images.githubusercontent.com/27956839/194897125-414108d3-78e6-43e1-971c-633d3a4b3665.png)

**Comment by Mazhoon** [comment]
Puavo-pkg available from [O2249 - Gratianopolis](https://changelog.opinsys.fi/en/opinsys/bullseye/index.html#opinsys-os-opinsys-bullseye-2022-12-08-085623-amd64) onwards.
