### ISSUE TITLE
Problem formatting an usb stick

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#607]
I am using Puavo opinsys-os-opinsys-bullseye-2022-10-06-105238-amd64 and I can't format an usb stick. I get the usb stick on the desktop, I open the files window and I try to get the formatting dialog by right clicking on the name of the usb stick. No dialog opens. 

I tested this problem in guest mode and with my test user paul.panther who can administrate the Puavo device. 
I tested different sticks and both usb ports of my pool002.einszueins.opinsys.fi
And I tested two differend Puavo devices ... the other one was md-lap-3011.magdeburg.opinsys.fi 

Where is the problem? What should I do?

Best regards,
Ralf

![puavo-formatting-usb-stick](https://user-images.githubusercontent.com/27956839/196193847-0a0276b3-5280-4557-9739-88218a68f6a0.png)

**Comment by Mazhoon** [comment]
This should be fixed in next Bullseye version with https://github.com/puavo-org/puavo-os/commit/ebfdc1a8fd6ea98358a85778cf7c170dda3809e1

**Comment by ralf-krause** [comment]
Thanks!
