### ISSUE TITLE
Veyon menu opens in finnish language

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#608]
I activated the veyon tool for classroom management to test it on my Puavo device pool002.einszueins.opinsys.fi.

I get an icon in the bottom line of my Puavo desktop near the support icon. The veyon menu is in finnish language in opinsys-os-opinsys-bullseye-2022-10-06-105238-amd64. Normally all other programs are running in german language. The veyon teacher screen seems to be okay and it's in german language. 

![veyon-finnish](https://user-images.githubusercontent.com/27956839/196860762-12d72de3-bc1b-4c26-a90e-f127c498c052.png)

![veyon-teacher](https://user-images.githubusercontent.com/27956839/196861630-08f0d601-be35-41b3-b493-48a28383aeb0.png)

**Comment by juhaerk** [comment]
Thank you for this bug report.  This was fixed in https://github.com/puavo-org/puavo-os/commit/ffaa97219955408ba53d75a5b71c21505a2b4de9 and the fix will be in later system images.
