### ISSUE TITLE
Surface Go 3 cameras

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#619]
Front and the back side cameras do not work. 

https://github.com/linux-surface/linux-surface

**Comment by ralf-krause** [comment]
Hi Antti, 
did you test the patches from https://github.com/linux-surface/linux-surface/releases/tag/debian-6.5.6-3  with the Puavo Bookworm image and the Microsoft Surface Go 3? I hope we will get it running.
Ralf

**Comment by tuomasjjrasanen** [comment]
I tested with 6.5.7-surface-2 plus couple of other additions and both cameras seem to work just fine. I'll investigate how to incorporate all necessary bits into the image wihtout bloating it too much.

**Comment by tuomasjjrasanen** [comment]
Ok, I think I managed to solve this in #638 , which is now waiting for a review.

**Comment by tuomasjjrasanen** [comment]
There's still something to be done to get the camera work on both Firefox and Chrome. I'll investigate and try to come up with a fix.

**Comment by tuomasjjrasanen** [comment]
With these 3 linked PRs, cameras seem to work also in Firefox.

Chorme support is still work in progress.
