### ISSUE TITLE
Opening puavomenu via touchscreen always opens virtual keyboard

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#620]
This is a usability issue and desktop menu should not open the virtual keyboard when it is opened.

**Comment by tuomasjjrasanen** [comment]
@asokero Can this be considered as solved (closed) now?

**Comment by tuomasjjrasanen** [comment]
@asokero Ping, is this resolved?

**Comment by asokero** [comment]
This is done, tested working and being used in production versions.
