### ISSUE TITLE
Arduino IDE 2.2.1

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#624]
Dear developers,
Puavo comes with an legacy version of the Arduino IDE. Yes, Arduino IDE 1.8.19 from 2021 is the latest version in Debian but the current version is Arduino IDE 2.1.1. Arduino 2.0 started in 2021 and it got a lot of new features and libraries in 2021, 2022 and 2023.

The most used Arduino board in schools is currently the Arbuino UNO R3. The first Arduino board was developed in 2005. The tutorial "Getting started with Arduino (1st edition)" was released in 2008 and this tutorial shows the programming with Arduino IDE 1.0. All the old Arduino boards until.2021 can be coded with Arduino IDE 1.8.19.

But there are a lot of newer boards which are developed by Arduino. There are new boards Arduino IoT and since last month the Arduino UNO R4. In some cases the newer boards are using newer processors and the differ from the old processors ATmega168 and ATmega328. Yes, these processors need the new Arduino IDE 2.1.1.

The new Arduino UNO R4 Wifi is very interesting for schools. It comes with a faster processor, more internal memory, a Wifi module, Bluetooth, and a 12x8 led matrix. And it costs less than 30 Euro. A very nice hardware for schools. https://store.arduino.cc/products/uno-r4-wifi

Please add the new Arduino IDE 2.1.1 as a Puavo package so the installation can be configured.
https://www.arduino.cc/en/software
https://github.com/arduino/arduino-ide/releases

Best regards,
Ralf

**Comment by ralf-krause** [comment]
Meanwhile the Arduino IDE 2.2.1 is released.

https://www.arduino.cc/en/software
https://github.com/arduino/arduino-ide/releases/tag/2.2.1

**Comment by ralf-krause** [comment]
Does it help that there is an Arduino IDE 2.2.1 AppImage for Linux?

**Comment by asokero** [comment]
Hey, sorry for the delay. There is now a puavo-pkg installer for Arduino Ide 2: https://github.com/puavo-org/puavo-os-pkg/commit/64f37150cfca6bdcf3533a88c4f339010a194b24

 It most likely will not be in the included inside the next image due to its size. But the app can be installed "on-the-side" via puavo-conf in the next production release.

**Comment by ralf-krause** [comment]
Hey Antti, it wasn't my intention to get Arduino IDE 2.x  inside the Puavo image. Thank you very much for the option with PuavoConfig!

**Comment by ralf-krause** [comment]
I tested the Arduino IDE 2.2.1 with  opinsys-os-opinsys-bullseye-2023-11-02-113644-amd64 (Roma) und opinsys-os-opinsys-bookworm-2023-11-03-091807-amd64 and it works fine. I just got a new Arduino Uno R4 Wifi.
