### ISSUE TITLE
Thymio Suite 2.4.0

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#625]
Dear developers,

the Thymio Suite 2.3.2 is a additional package for Puavo. The Thymio Suite 2.4.0 was released in October, 2022. The new version comes with several new features. The students can program with a newer Scratch version and they can use Thonny. Thonny is an integrated programming environment for Python.
https://github.com/Mobsya/aseba/releases

Best regards, Ralf

**Comment by ralf-krause** [comment]
Dear Puavo developers,
I found that the Thymio Suite 2.4.0 should be a new package. 
https://github.com/puavo-org/puavo-os-pkg/commit/1b21dc970683437070d0c78ce2f13c98da708afe
I tried to get this with my Puavo test device but the Thymio Suite 2.3.2 is still installed.
In terminal I write `sudo puavo-pkg-update` and for the Thymio Suite I get the following messages

```
PUAVO-PKG-UPDATE: installation directive on thymiosuite is: latest
PUAVO-PKG-UPDATE: downloading https://cdn.opinsys.fi/puavo-pkg/thymiosuite/latest.tar.gz.gpg
PUAVO-PKG-UPDATE: verifying https://cdn.opinsys.fi/puavo-pkg/thymiosuite/latest.tar.gz.gpg
PUAVO-PKG-UPDATE: we already have thymiosuite with id d26b0263265bbc55a49927ffe38e0043
```

The id is the id for the Thymio Suite 2.3.2.
What should I do to get the Thymio Suite 2.4.0?

I updated to Puavo Ovilava opinsys-os-opinsys-bullseye-2023-08-18-105516-amd64 yesterday.

Best regards,
Ralf

**Comment by ralf-krause** [comment]
Hi,
today the correct version of the Thymio Suite seems to be installed but the application does not start.
```
PUAVO-PKG-UPDATE: installation directive on thymiosuite is: latest
PUAVO-PKG-UPDATE: downloading https://cdn.opinsys.fi/puavo-pkg/thymiosuite/latest.tar.gz.gpg
PUAVO-PKG-UPDATE: verifying https://cdn.opinsys.fi/puavo-pkg/thymiosuite/latest.tar.gz.gpg
PUAVO-PKG-UPDATE: we already have thymiosuite with id f1fccb62ff19151f5bc8d6273e722d52
```
The id changed to the id for the Thymio Suite 2.4.0.
To start the application I was looking for the application command. I can't say if I found the correct one
```
sudo /usr/local/bin/thymiosuite
```
Now I get an error message for a missing runtime file.
```
Fehler: runtime/org.kde.Platform/x86_64/5.15 ist nicht installiert
```
Best regards,
Ralf

**Comment by ralf-krause** [comment]
I just tried to start the Thymio Suite with the older Puavo image "Novaesium" opinsys-os-opinsys-bullseye-2023-06-09-092932-amd64 and got the same error message for the missing runtime file.

**Comment by ralf-krause** [comment]
I just tried to start the Thymio Suite with the older Puavo image "Novaesium" opinsys-os-opinsys-bullseye-2023-06-09-092932-amd64 and got the same error message for the missing runtime file.

**Comment by ralf-krause** [comment]
Any idea for the missing runtime/org.kde.Platform/x86_64/5.15?

**Comment by juhaerk** [comment]
Thanks for the report! Yes, there was a bug. It was not in the old version, it was not in the new version, which is why I did not catch it. What was broken was an *upgrade* from an old version to a new version.

This should be fixed now, wait for systems to update themselves, and try again.

**Comment by ralf-krause** [comment]
Hi Juha,
I can load the new Thymiosuite now. It's fine! It comes with a newer Scratch and with Python. Great. Thank you very much!
Ralf

**Comment by ralf-krause** [comment]
Hi Juha,
I want to tell you that I just started the Thymio Suite with the new Bookworm image opinsys-os-opinsys-bookworm-2023-09-20-105321-amd64. Great! It works!
Ralf
