### ISSUE TITLE
Factory reset fails to delete the home dir

### ISSUE THREAD

**Issue by tuomasjjrasanen** [puavo-org/puavo-os#631]
`puavo-reset-laptop-to-factory-defaults` fails to delete the home directory and leaves some tracker- and icc-related files behind, for unknown reason. All other reset steps succeed, but the overall execution fails causing laptop **not** to reboot. However, in practice, the laptop is reset and after a reboot, the system boots up just like the reset would have been completely successful.

**Comment by tuomasjjrasanen** [comment]
I don't know if this affects just Bookworm or Bullseye too.

**Comment by ralf-krause** [comment]
Can you write which Puavo image you used? The Puavo image Poetovium has problems to login a new user who has no home directory . This problem is fixed with the current Puavo image Qus. Look at https://changelog.opinsys.fi/de/opinsys/bullseye/

**Comment by juhaerk** [comment]
Yes thanks!

**Comment by juhaerk** [comment]
Hi Tuomas does the "apply delete_file_cmd to all files"-fix affect this one as well? I do not know about this situation, are they related?

**Comment by tuomasjjrasanen** [comment]
@juhaerk Well, at first I thought that it would, but the error. which is sporadic in nature, is encountered when deleting the actual home directory. The deletion happens in two steps: first, all files in a home directory are deleted and then the directory itself is deleted.

The directory is deleted with `rm -rf` which should take of deleting everything recursively, yet still, sometimes the command fails with `rm: cannot remove '/home/user': Directory not empty`.

To me, that tells how  `rm -r` implemented: it first tries to remove all contents recursively and then finally the directory itself, but at the time when `rm -r` has deleted all the contents it saw at the beginning of its execution and is about to delete the directory node itself, a new content has appeared and hence the removing the directory node fails. That's because, the operation is not atomic and someone is constantly writing to the home directory.

Well, there are quite many processes running in the user's desktop session: colord, tracker, etc. In other words, the race condition is inherent.

How to fix this?

Well, obviously the best solution would be to get rid of the race condition in the first place, i.e. to terminate the user session completely, to make sure no process writes to /home (or any other dirs which would need to be deleted completely) during the factory reset. That would probably require switching (after user confirmation) to a dedicated "factory reset mode" and then doing the actual reset in that context. There are many ways how that mode could be implemented, but the main goal is to ensure the system is running only a minimal set of processes in controllable fashion to not interfere with the factory reset process.

But that's probably not a feasible plan at this point.

So, I'll suggest that we adapt the current `puavo-reset-laptop-to-factory-defaults` to _be aware of the race condition_ and try to deal with it. After all, the effects of the race condition are quite limited (seem to affect only deletion of the home dir node after it's basically already empty, from user's content anyways) and they are quite easily circumvented (terminate known racers beforehand AND PERHAPS try couple of times to delete the dir node).
