### ISSUE TITLE
Chromium to use system windows title bar on big touchscreen

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#64]
- Use system title bar and borders as default Preference

https://www.chromium.org/administrators/configuring-other-preferences

Setting for this should be: `"custom_chrome_frame":false`

**Comment by asokero** [comment]
Create a file:
`/etc/chromium-browser/master_preferences`

```
{
   "custom_chrome_frame": false
}
```

**Comment by tuomasjjrasanen** [comment]
Does not seem to have any effect. I modified ``/usr/lib/chromium/master_preferences`` (because that is the correct file path in Debian's chromium package) and tried with a fresh guest user profile.

**Comment by tuomasjjrasanen** [comment]
Actually, it needs to be in ``/etc/chromium/master_preferences``. Checked from the source code.

**Comment by tuomasjjrasanen** [comment]
Once more time boys! The contents of ``/etc/chromium/master_preferences`` must be:

    {
      "browser": {
        "custom_chrome_frame": false
      }
    }
