### ISSUE TITLE
Cryptomator Update 

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#641]
Dear developers,
I found that the Cryptomator package should get an update from version 1.6.15 up to version 1.11.1.
https://github.com/cryptomator/cryptomator

Ralf

**Comment by eluttine** [comment]
Thanks for reporting it @ralf-krause. The Cryptomator has been [updated](https://github.com/puavo-org/puavo-os-pkg/commit/a129d13dcdec6d686efd199ef23eb0b1320951b6).
