### ISSUE TITLE
Chromium policies and command line parameters for big touch

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#65]
To make Chromium more usable in this use case the browser should be simplified as much as possible.
- Prevent printing (at least in this point it is not needed)
- Remove google sign in
- Remove unnecessary pop-up requesters and infobars

**Comment by asokero** [comment]
Policies - ``/etc/chromium/policies/managed/test-policies.json``
``{
"PasswordManagerEnabled": false,
"SyncDisabled": false,
"PrintingEnabled": false,
" SigninAllowed": false
}
``

Commandline flags
- ``--disable-infobars``

**Comment by tuomasjjrasanen** [comment]
I think disabling info bars is quite generic need, not bound to bigtouch desktops. There are some other pretty annoying popups/infobars, such as "You can search from with Google" -message. We already have `--no-default-browser-check` covers a subset of features of what `--disable-infobars` does.

I'll open a another issue for this. Those policy changes remain to be tracked by this issue.

**Comment by tuomasjjrasanen** [comment]
See #66

**Comment by asokero** [comment]
Not relevant anymore.
