### ISSUE TITLE
Add etcher to make usb sticks and microSD cards

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#660]
I can't say if a Puavo pkg for etcher would be useful. There are some cases we need etcher to make usb sticks and microSD cards. 

- If you want to test a new linux distribution with a life medium you will download the installation image and then you will copy it on an usb stick. Start your home pc with the life medium.
- If you want to install a Raspberry Pi you will download the installation image and you will copy it on a microSD card. The Raspberry Pi starts with this microSD card. The Raspberry Pi has a lot of different system os you can use in school for your experiments.

Yes, it's really easy to get etcher on a Puavo device. Download the etcher AppImage and set the execution bit. Do I need to have administration rights on the Puavo device to do this? 

Yes, for school projects the etcher AppImage will stay in place in your local personal home directory. And if you take the same Puavo device next time the etcher AppImage is just there and you do not need to get it once more.

There ist still an open issue for etcher https://github.com/puavo-org/puavo-os/issues/414

Best regards,
Ralf

**Comment by ralf-krause** [comment]
BalenaEtcher is added as a PuavoPkg for Venetiae "opinsys-os-opinsys-bullseye-2024-03-05-100921-amd64". 

To copy a disk image to an usb stick or a microSD card you need to have admin rights for the Puavo device. These right will only work with a primary user and a personally administered device. Could there be a chance to get the app working also for normal users at school?

**Comment by asokero** [comment]
Hey,

Yes this is the reason why Etcher has not been made available as puavo-pkg before. As it has been requested every now and then, we decided to do it although it will have limitations. The application/operation requires such permissions that it can only be used by primary user on a personal laptop. I do not think that this can or will be changed in the foreseeable future. Technically this might be possible, but most likely it could open some possible security vulnerability which is a risk that we will not be willing to make.

**Comment by ralf-krause** [comment]
Hey Antti, thank you for implementing Etcher and for your clear comment about the using requirements.
