### ISSUE TITLE
Wifi chooser is too dark in Bookworm

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#661]
We can't use the wifi chooser on a Puavo device with Bookworm. The list of the existing wifi networks is in dark grey colour on a black background. This is not very useful!

![puavo-ookworm-wlan-chooser](https://github.com/puavo-org/puavo-os/assets/27956839/854c6c9a-4ec8-435f-9438-caa2ba24f06c)

**Comment by asokero** [comment]
Hey Ralf,

Thanks for reporting! This is a known issue as Bookworm is still under development. Theme fixes will be done sometime later as there are several other issues also related to this,

**Comment by asokero** [comment]
This will be fixed in the next image release.

**Comment by ralf-krause** [comment]
Yes, I found the new image and the wifi chooser looks fine! Thanks!
