### ISSUE TITLE
puavo-pulseaudio-get-puavoconf does not work on Bookworm

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#662]
```
:~$ puavo-pulseaudio-get-puavoconf
Could not determine the default sink!
Could not determine the default source!
```

**Comment by sarrchri** [comment]
Just in case, I tested that this indeed does not happen on Bullseye, so it is Bookworm specific.
The issue was caused by `pactl info` output being automatically localized to the session/system language.

Fixed as of commit 0c4602e.
