### ISSUE TITLE
Chrome asks for setting a password

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#663]
The Chrome browser asks for setting a password for a key chain.

Yes, you can type on "cancel" and you get the input window a second time. Yes, you can type "cancel" again to get the Chrome browser working. But next time you start the Chrome browser then you will be asked for the password again.

I get this problem with the Chrome browser in Bullseye (Ulpia Noviomagus Batavorum) and in Bookworm (Cesium)

**Comment by ralf-krause** [comment]
I also tested the Chromium Browser with the same result.

**Comment by ralf-krause** [comment]
The problem also exists for the latest Puavo image Venetiae "opinsys-os-opinsys-bullseye-2024-03-05-100921-amd64".

**Comment by asokero** [comment]
Could this be your user profile specific issue on an individual laptop? Have you tested it if it happens with some another user account / guest user or device?

**Comment by ralf-krause** [comment]
I tested this with the device md-test006 and the users ralf.krause, paul.panther and the guest user. 

Yes, the problem only comes up with ralf.krause. I left the password fields empty and clicked on the continue button. I got a message that with an empty password all the transmitions will get unsecure. The password box did not open again when I closed and reopened the Chrome browser. Okay, this should not be the problem for the moment. But after logging out and logging in with ralf.krause again the password box is shown again at the start of the Chrome browser.

What should I do? I deleted the folders /home/ralf.krause/.config/chromium and /home/ralf.krause/.config/google-chrome. I rebooted the device and logged in again with ralf.krause. And I got the same result ... the password box came up again.

Now I got a new idea. I tested a different device md-lap-3011 with the user ralf.krause. I got no password box when I started the Chrome browser. Okay, there seems to be a problem with the user settings of ralf.krause and the device md-test006. What should be done to repair the problem? Yes, I could delete the complete home folder ralf.krause. Do you have another idea?

**Comment by asokero** [comment]
This is just a guess, but one thing to test is see if there is something wrong with your gnome keyrings. You could take a look at Menu > Applications > Passwords and keys and see f there is something wrong with Chrome passwords (deleting these should be ok as they are automatically created when chrome is started).

**Comment by ralf-krause** [comment]
I opened the app and deleted the passwords in the default keychain. As soon as I start the Chrome browser, I am asked to set a password again.

If I press Enter twice, I probably create a blank password. In the app I see a new second default keychain with a "Chrome Safe Storage Control" key. For this key I can display the password "The meaning of life" which was automatically set. And when I log out from Puavo and log in again the setting for a password is asked again.

**Comment by ralf-krause** [comment]
Now I deleted the complete user folder ralf.krause from the home directory and restarted the device. Yes, I saved all documents on an usb stick before. The new login automatically created a new user folder. 

Now the browsers Google Chrome and Chromium are starting without a password dialog.

**Comment by asokero** [comment]
Hey,

This same bug appeared on our own tests and apparently it is caused by the Citrix ica client which somehow corrupts the gnome keyring. And I took a look and you actually have ica client installed on your test device. Therefore this is most likely the root cause for this bug. At the moment it seems that there is not much we can do for this, but time will tell.
