### ISSUE TITLE
Arduino 2.3

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#665]
Dear Puavo developers,
I can't say how many schools are using the Arduino IDE but I hope that playing with hardware will increase. Arduino is open hardware and the software is open source. There are a lot of very exciting projects.

The Arduino blog announces the new version: "We’ve just released [Arduino IDE 2.3](https://www.arduino.cc/en/software), and along with the usual list of bug-fixes and improvements, this new version marks the end of the experimental phase for the debug feature – which is now stable and fully incorporated into the IDE!"
https://blog.arduino.cc/2024/02/07/ide-2-3-is-out-and-youll-love-the-new-debugging-features-in-it/

Ralf

**Comment by asokero** [comment]
Hey Arduino 2.3.x will be update to the puavo-pkg soon (already has been but will be in production later.).

**Comment by ralf-krause** [comment]
Great! Thank you very much!
