### ISSUE TITLE
Enable Web Bluetooth by default on Google Chrome

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#667]
Web Bluetooth is being used by some robotics programming environments and Physics data collection and analysis web applications (Vernier/PASCO). On linux this is not enable by default in chrome but this can be activated via a) Chrome flags b) commandline argument (`google-chrome-stable --enable-features=WebBluetooth`).

PuavoOS should have a new puavo-conf to configure these Chrome flags and the web bluetooth could be enabled by default.

**Comment by ralf-krause** [comment]
Great! Please enable this parameter also for Chromium.

The parameter must be enabled for Lego Spike https://spike.legoeducation.com and for the littleBits CodeKit https://fuse.littlebits.com/coding .

**Comment by juhaerk** [comment]
Fixed: https://github.com/puavo-org/puavo-os-pkg/commit/60dfc339fcaa3b1a166442c75d3783af0dc51b13 and https://github.com/puavo-org/puavo-os/commit/4fe5535c236c9f764e2c27cad31c7b56d65c35df

**Comment by ralf-krause** [comment]
Thank you very much!

How will this work? Do we need to set an extra PuavoConf parameter in PuavoWeb? 
Or is the parameter already activated when Puavo has Chrome and Chromium installed?

**Comment by ralf-krause** [comment]
Great! 
I found the new image and I tested the Lego-Spike software in guest mode. There is no need to enable the WebBluetooth anymore. It is enabled by default for any user in Chrome and in Chromium.
