### ISSUE TITLE
Add option for icon theme selection to Gnome system settings

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#669]
As in Bullseye version on Puavo OS desktop there should be a way for the user to select the desktop icon theme in the system settings. In Puavo OS Bullseye we had our own appearance menu, but since then Gnome has added their own. We could merge the old functionality to the current Appearance menu.

As before, we could offer a few alternative themes that are known working. Somethig like....

![Bookworm-appearance-settings](https://github.com/puavo-org/puavo-os/assets/1162097/7a3321de-4c3f-45fc-a07e-527cf0daa09f)

**Comment by tuomasjjrasanen** [comment]
I took the freedom to change the set of selectable icon themes a bit; changed Breeze to Adwaita because they seem to be pretty much the same, expect Breeze had quite many missing icons: folder, wifi, privacy...

**Comment by tuomasjjrasanen** [comment]
Can be tested locally like so:
```
git fetch origin
git checkout debs_gnome_control_center_add_icon_theme_chooser_to_appearance_panel
cd debs
make debs-build-gnome-control-center
# sudo dpkg -i resulting .deb files
```

**Comment by tuomasjjrasanen** [comment]
PR #685 adds sv, fi and de translations and icon theme labels. It also tightens the layout to fit all icon themes on the same row.

![kuva](https://github.com/puavo-org/puavo-os/assets/5660/b0e32e76-4079-4cd9-a92c-9a6c2b080888)

![kuva](https://github.com/puavo-org/puavo-os/assets/5660/983c8b8f-7a40-46c1-b831-c65783b6723c)

![kuva](https://github.com/puavo-org/puavo-os/assets/5660/219daed2-0f43-49c2-8edd-5d83588c4980)

![kuva](https://github.com/puavo-org/puavo-os/assets/5660/cb35e5ff-626a-4dd9-bdb6-b99e143cf9d9)

**Comment by tuomasjjrasanen** [comment]
@asokero What about this one?

**Comment by asokero** [comment]
It is perfect, closing.
