### ISSUE TITLE
Puavomenu scaling on low resolutions

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#672]

**Comment by tuomasjjrasanen** [comment]
PR #687  introduces two modes (two sets of dimensions) in which puavomenu can run: lowres and highres. It selects the optimal mode **during startup** based on the primary monitor resolution of the default display. Pixel count less than 1280x800 is lowres, greater or equal is highres. It also relaunches itself when resolution is changed.

**Comment by tuomasjjrasanen** [comment]
@asokero Is this resolved?

**Comment by tuomasjjrasanen** [comment]
@juhaerk Perhaps the fix should have been merged to bullseye too?

**Comment by juhaerk** [comment]
This is good but not taking into Bullseye, thanks.
