### ISSUE TITLE
Handbrake is not in Puavo menu

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#673]
I found that the Handbrake application is installed by default on Bullseye and Bookworm but it is not in the Puavo menu. To start the software you need a media file which you try to open with a right mouse click. Yes, to open it with another application. Handbrake needs to be in the Video and Audio menu.

You can also start Handbrake in the terminal with the command `handbrake`.

**Comment by ralf-krause** [comment]
Please update the Handbrake app and add it to the Puavo menu.
Currently Puavo comes with Handbrake 1.3.1 (01.2020). You should update to Handbrake 1.8.0 (05.2024) with a lot of new or updated multimedia encoders. https://github.com/HandBrake/HandBrake/releases/tag/1.8.0

**Comment by asokero** [comment]
Yes we can add the Handbrake to the menu. We will still stick with the Debian version as there is not any upstream source to create a puavo-pkg with reasonable work as this is still a minority application. Debian does not offer any never versions of the software in the backports at the moment. If there is a concrete problem/showstopper with the aaplication we might consider using the upstream version (if it is even possible). There is also winff available for video conversions in the menu.

**Comment by ralf-krause** [comment]
Yes, in Bookworm I get a better Handbrake 1.6.1 than in Bullseye.
What do you think about Handbrake 1.7.2 from Debian testing?  https://packages.debian.org/trixie/handbrake

The WinFF app is very old and not usable for schools when it shows the Flash format for website videos. Flash video are not usable on web pages. You should remove WinFF from Puavo.

Ralf

![winff](https://github.com/puavo-org/puavo-os/assets/27956839/04370f2c-9206-46e7-9de5-c3e8d27e08da)
