### ISSUE TITLE
Puavo-pkg installer for S4A

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#679]
https://s4a.cat/

**Comment by ralf-krause** [comment]
Hi Antti,

I did some tests with S4A running on my personally administered Puavo device md-lap-3011.
I downloaded the debian package from https://s4a.cat and installed it on my device.

S4A is a Scratch modification that allows for simple programming of the Arduino open source hardware platform. It provides new blocks for managing sensors and actuators connected to Arduino ... in my test scenario it was an Arduino UNO R3.  I can't say if S4A will work with newer Arduino boards than the Arduino Uno R3.

The main aim of the project is attracting people to the programming world. The goal is also to provide a high level interface to Arduino programmers with functionalities such as interacting with a set of boards through user events. S4A is running on the computer and the firmata commands are permanently send from the computer to the board. No, the Arduino can't be used without S4A in this case.

S4A is a very old project based on Scratch 1.4. Scratch 1.4 is from 09.2009. The development of S4A ended 01.2015.

Best regards,
Ralf

![puavo-s4a-20240507](https://github.com/puavo-org/puavo-os/assets/27956839/9507710c-2b32-4516-a305-5fe6d3d4c956)

![arduino-breadboard-20240507](https://github.com/puavo-org/puavo-os/assets/27956839/51fdb8e4-c65b-4637-a27a-a856a68a708a)

**Comment by ralf-krause** [comment]
Hey Antti,

in my next session I tested Snap4Arduino on https://snap4arduino.rocks/

Snap4Arduino is a Snap! extension, a full Snap! implementation that can interact with the physical world, through many types of electronic devices, especially those compatible with Arduino. I tested the same Arduino UNO R3 as before.

Snap! is a broadly inviting programming language for kids and adults that's also a platform for serious study of computer science. It is inspired by Scratch, written by Jens Mönig and Brian Harvey and presented by the University of California at Berkeley.

Snap4Arduino and Snap! are living software projects. The current online version https://snap4arduino.rocks/run/  is v9.2.1. There are also desktop versions for macOS, windows, and Linux. The supported Arduino boards are 8 bit boards (Uno, Nano, Mega, Leonardo, Micro) and 32 bit boards (Due, 101, ESP8266, NodeMCU). You also need the Firmata firmware for the Arduino … look at https://github.com/jguille2/SA5/blob/master/README.md

My experiments were the same as I did with S4A. A led is switched on and off by pressing the keys 1 and 2 on the laptop keyboard. And pressing the button on the breadboard makes a sound on the laptop audio. The program runs in the Chrome browser and no additional software is installed in the laptop. I tested the Arduino programming also with Chrome on a MacBook with a M1 processor. 

![snap4arduino-20240507a](https://github.com/puavo-org/puavo-os/assets/27956839/e125b23a-e851-4dc4-9f7a-ccbe1309be75)

**Comment by ralf-krause** [comment]
Hey Antti,
you can find a cool project "my interactive garden" using the Arduino, the grove senor kit for Arduino and Snap4Arduino.

https://www.cs.uni-potsdam.de/myig/snap4arduino.html
https://www.cs.uni-potsdam.de/myig/uploads/Anleitung-Grove.pdf
https://wiki.seeedstudio.com/Grove_Starter_kit_for_Arduino_101/
https://wiki.seeedstudio.com/Grove_Smart_Plant_Care_Kit/

Best regards,
Ralf

**Comment by ralf-krause** [comment]
Hey,
I found the new Puavo image Apulum and the new PuavoConf parameter puavo.pkg.s4a ... no, currently S4A does not load.

**Comment by asokero** [comment]
Hey @ralf-krause thanks for your comments and suggestions. Yes the s4a support has been added as this is the version customer will need in hes course. We can take a look at the other suggestions separately. S4a not yet delivered in the OpinsysOS cdn server but will be there shortly. To test you will need to install manually from the puavo-os-pkg repo.

-Antti
