### ISSUE TITLE
Nextcloud client login window always opens when opening nautilus windows

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#690]
If Nexcloud client is installed and user opens Nautilus, it always pops up the Nextcloud login window. This is naturally unwanted behaviour.

**Comment by asokero** [comment]
Most likely the same issue as here: https://github.com/nextcloud/desktop/issues/6389

**Comment by Mazhoon** [comment]
Fixed with https://github.com/puavo-org/puavo-os/commit/7d6941f41f422d63587ed86b8b27998568125e01 , would also be fixable by removing /usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini

**Comment by Mazhoon** [comment]
Related earlier report at https://github.com/nextcloud/desktop/issues/1982
