### ISSUE TITLE
KDE/Qt theming in Bookworm

### ISSUE THREAD

**Issue by Mazhoon** [puavo-org/puavo-os#694]
KDE/Qt theme unification with Gnome was done with Kvantum in Bullseye
Some of the pieces are there in Bookworm, too: https://github.com/puavo-org/puavo-os/blob/8eaa9cce926eae6f3720af30ecf0d618bd4c6cbc/rules/themes/manifests/init.pp#L50 https://github.com/puavo-org/puavo-os/tree/8eaa9cce926eae6f3720af30ecf0d618bd4c6cbc/rules/themes/files
Kvantum is set as the default theme. However, it still uses Arc-lookalike as the target theme, that might need updating to correspond to Puavo Bookworm UI looks.

Additionally, the light/dark selection was done by writing a setting to use light or dark version to a Kvantum config file under user config path. This was done by gnome control center, related changes in commit https://github.com/puavo-org/puavo-os/commit/413aaa8a04439184829becdfc70c31584218dfcc and some following ones. Corresponding functionality is not yet implemented in Bookworm.

**Comment by tuomasjjrasanen** [comment]
The correct user config filepath in Bookworm is `~/.config/Kvantum/kvantum.kvconfig`.

**Comment by tuomasjjrasanen** [comment]
I don't know what is the reason why we use Arc as Gtk theme, and Yaru as GNOME Shell theme, but I think that using KvArc for Qt is aligned with that logic.

Anyways #702 brings in patches which make gnome-control-center change Qt Kvantum theme from default to dark and back when the color scheme is changed.

**Comment by Mazhoon** [comment]
Just as a note, if one would want to switch to Yaru as application theme, there seems to be a potential Kvantum theme available at https://github.com/GabePoel/KvYaru-Colors

**Comment by tuomasjjrasanen** [comment]
@Mazhoon Is this resolved?
