### ISSUE TITLE
LibreOffice in Puavo

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#708]
Dear Puavo developers,
I found LibreOffice 24.2 in the Puavo Bookworm image "Cesium". This was very nice!  Why did you go back to LibreOffice 7.4.7 in the current Puavo Bookworm image "Fermium"? LibreOffice recommends using 7.6.7 for conservative users and 24.2.3 for technology enthusiasts and pioneers. Puavo Bookworm will run two years or more so you could start with LibreOffice 24.2.3.
Best regards,
Ralf

**Comment by asokero** [comment]
Hey Ralf,

This is apparently due to some big general cleanup work in the previous image that seemed to take a little too much along other changes. We'll take a look at this in the upcoming days.

**Comment by Mazhoon** [comment]
Bookworm returned to backports LibreOffice in June with https://github.com/puavo-org/puavo-os/commit/31c4608897c5891cc544a908dfb3d758928ba784 , available in released O2425, closing.
