### ISSUE TITLE
Cups-pki-invalid problem on bookworm

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#723]
Looks like there is some problem with cups and certs (/etc/cups/ssl/boot3.local.crt) when moving from bullseye or older to bookworm. Most likely related to this https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1973441

**Comment by juhaerk** [comment]
I believe this problem has been fixed in commits: https://github.com/puavo-org/puavo-os/commit/6ca9a45e6c5b8e3f17ceabb425fc36db3519312c and https://github.com/puavo-org/puavo-os/commit/a9a6425f46bfe3b118231cf10ee80df90945e486
