### ISSUE TITLE
Chromium needs to be updated

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#729]
The current Puavo Bullseye comes with Chromium 120. This is rather old.

Linux Mint 21.3 comes with Chromium 126 which works fine.
macOS and Window have stable Chromium 127.

Please update Chromium for Puavo Bullseye with all codecs.

**Comment by Mazhoon** [comment]
I believe it is unlikely that Chromium would get updated in Bullseye, as, unlike Chrome and Firefox that are puavo-pkgs, Chromium is the version from Debian repositories (I think partial goal is to have at least one major browser via non-pkg route), and no newer packages are provided for Bullseye upstream: https://packages.debian.org/bullseye/chromium

**Comment by Mazhoon** [comment]
Confirming: No separate Chromium updates for Bullseye. Migrations to Bookworm will take place relatively soon, Bookworm has regularly updated Chromium from Debian repositories.
