### ISSUE TITLE
Add launcher for Greenfoot

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#744]
Greenfoot ide has a puavo-pkg installer, but it is missing a puavomenu launcher.

**Comment by ralf-krause** [comment]
I wonder that you write to add Greenfoot. In the changelog for the current Puavo version "Iridium" we can read: "Add: Ability to install the Greenfoot programming environment".  Yes, I can install Greenfoot 3.8.2 in Puavo. There is a puavoConf parameter for Greenfoot and I added this puavoConf parameter on my device md-test006. I can start Greenfoot in the terminal. But there is no menu item for Greenfoot.

**Comment by asokero** [comment]
Yes, as the topic and the description says, this issue is a reminder to add the missing menu launcher for the next image.

**Comment by asokero** [comment]
Done.
