### ISSUE TITLE
Make puavo.grub.windows.enabled = false more effective

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#745]
Using puavo-conf ```puavo.grub.windows.enabled = false```  should prevent dual booting to Windows on a puavo laptop. Currently it hides the Windows option from Grub bootmenu, but it is possible to figure out and find an alternative way. Booting to Windows whent the setting has been aplied should not be easily possible.

There already is an upcoming pull reguest for this: https://github.com/puavo-org/puavo-os/pull/742

**Comment by juhaerk** [comment]
Done: https://github.com/puavo-org/puavo-os/pull/742
