### ISSUE TITLE
A new Puavo Exam Mode for making Abitti 2 (and other similar url based online exams)

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#746]
An exam mode is needed for making online exams. The first target is to create 
- possibility for user to access an url exam from the normal desktop by typing the exam url manually
- the exam environment should be simple desktop without access to local apps/files
- the environment won't let access any other website
- Desktop has basic volume controls and ability to exit exam 
- the mode should be activated per device via puavo-conf

This is the first prototype version to be added to the image. For the next steps and features we will create new issues.

**Comment by juhaerk** [comment]
We have this now, a kind of alpha-version that may be useful in some situations.

**Comment by juhaerk** [comment]
Hi! Thanks for your interest in the exam mode ;-)

I do not think we do bug bounties or at least we do not have a formal bug bounty program.

In regular use mode one can install software in user home directory and run it, that is just normal system behaviour.

Running arbitrary software in the exam mode should not be possible, except in case it is explicitly allowed. Thus, we consider that "relatively easy ways to install and/or use software not preinstalled by Puavo on the exam mode" should not be possible, or at least the design criteria is that something like that should not be easy. However, exam mode is still quite in early development and at least I expect these issues to exist. We know at least one such a problem ourselves. We do not yet use any "tougher" sandboxing techniques in the exam mode, even though something like this is in the plans. This should make cheating harder.

Please tell us what you have found. I think it should be okay to disclose it here, publicly. If valid, we are interested in fixing those issues, improving the security of the examination mode. You may contact us privately as well, in case you think that is more appropriate.

**Comment by juhaerk** [comment]
My previous reply was to a comment that has been removed. Apparently the poster was not interested in discussion, only money? Seriously?

**Comment by juhaerk** [comment]
> If you want a really honest answer then I do not want to disclose information that could potentially lessen my "fun" without a good reason to do so.

It would make the world a better place, that is a good enough reason. At least it motivates me. But you may try to have your fun.

> By the way, setting a wallpaper from Puavo OS' Nautilus file manager does not seem to work.

True. I do not know why. The "standard" Gnome way works and I think that is what people will usually try.

> Wouldn't enabling disk encryption by default on Puavo OS to be a good default? Most devices with Puavo OS installed are probably laptops. It should be good for security, especially since laptops aren't very hard to steal.

Absolutely! But this is hard to do properly. The difficulty is not simply "enabling it", but questions such as: who is managing the encryption keys and how, should the encryption be tied to a user password or should there be a boot time prompt for it, how do we recover from situations where user has lost his keys (has forgotten his/her password/passphrase), and such. We are currently working on this feature based on TPM2, and those will hopefully come in place with fresh Debian Trixie installations. But we'll see. See our puavo-os `trixie`-branch for latest developments.

**Comment by juhaerk** [comment]
> > > By the way, setting a wallpaper from Puavo OS' Nautilus file manager does not seem to work.
> > 
> > 
> > True. I do not know why. The "standard" Gnome way works and I think that is what people will usually try.
> 
> This should be fixed.

Sure, but we have a million things to do. Could you fix it for us, maybe we will take the fix in?

> Also, GeoGebra should be stylized as "GeoGebra" instead of "Geogebra" in Puavo OS.

Okay!
 
> Would it be realistically possible to have multiple desktop environments on Puavo OS? It would be nice to be able to use KDE Plasma.

KDE takes a lot of space so no, that is not realistic. We have i3. The desktop environment choice is normally locked but can be unlocked through our management system. Unlocking that should not be possible for normal users, but I suppose some hackers can manage to workaround that.

**Comment by juhaerk** [comment]
> > Sure, but we have a million things to do. Could you fix it for us, maybe we will take the fix in?
> 
> I'm not sure what causes the issue. Besides, I am not a programmer.

But you can become one! We all have to start from somewhere.

> By the way, why is i3 preinstalled if it is typically unusable?

It is used in unusual contexts. Our "USB factory" and "digital signage" modes use it.

**Comment by juhaerk** [comment]
> I have now found a way to become root in a terminal even with the restrictions on sudo.

Interesting! If your hack involves booting the system from a USB drive (or a network) and then modifying the filesystem, well, that is rather easy and yes, we know ;-)  You may check out my presentation on https://www.sfscon.it/talks/implementing-digital-examinations-in-free-software-systems/ It is not that we do not care, but defending against that is rather difficult and that is one reason why we still had open root permissions (half a year ago) to those who have a complete physical control of the machine (meaning they can take it home etc.). But, because of the demands of the examination systems, we are trying to make that harder, and a solution to that is encryption.

If you know a way to get root without booting another system, then we would like to know. Unfortunately you are not telling and you remove your old posts, so this looks like I am doing some crazy monologue. But please tell us what you did, look up our dev-email address from https://puavo.org
