### ISSUE TITLE
On puavo-ers profile turn off TCP Segmentation Offload (TSO) setting on ethernet devices

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#748]
By experience/research by YTL this seems to solve some network related problems for example on Intel I219 network devices. Reference here: https://github.com/digabi/ytl-linux/tree/main/ytl-linux-tso-off

**Comment by juhaerk** [comment]
Fixed in https://github.com/puavo-org/puavo-os/commit/72c299f2ef992f5f0f99a97aa5f2c9479cd90606
