### ISSUE TITLE
MicroBlocks needs to set user into the groups dailout and tty

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#759]
Dear developers,

I am testing MicroBlocks, a very nice programming software for physical computing. https://microblocks.fun
MicroBlocks is something like Scratch for microcontroller boards like Micro:bit, Calliope, Adafruit CircuitPlayground, Raspberry Pi Pico and a lot of other boards. MicroBlocks works in the Chrome browser so you do not need to install addional software. The Chrome browser uses WebUSB and WebSerial to connect to the board if it is connected via USB. And it uses Web Bluetooth if the board is connected via BLE.

The MicroBlocks software is for education. The lead developer is John Maloney who was one of the main developers from Scratch. https://microblocks.fun/about . The difference between Scratch and MicroBlocks is that Scratch can only program the Micro:bit v1 and some old Lego Bricks. And Scratch needs a static connection to the board while the program runs on the computer and the physical input and output connects to the board. In MicroBlocks the editor is on the computer and the program runs completely on the board. You need to load a virtual machine to the board and the editor sends some byte code to the board. If you disconnect the board from the computer the program can be started on the board without the computer. It's very great! I am playing with Micro:bit, Calliope and Adafruit CircuitPlayground Bluefruit.

Now comes the problem. The corrent user needs to be in the groups dailout and tty. On my test computer md-test006 I set these groups manually. Looking into /etc/group shows ralf.krause as a member of dailout and tty. It's no problem to do this manually for me and my account. But MicroBlocks should work in the schools with different users. 

Please find a fix for this problem. I should make teacher workshops using Puavo in the schools in Magdeburg.

Best regards,
Ralf

![microblocks-calliope-neopixel](https://github.com/user-attachments/assets/ab6dbd23-970f-43cf-b79f-e3dc5217e01f)

![puavo-groups-dial-out-tty](https://github.com/user-attachments/assets/7eb48786-6e6e-42a6-8c6e-da20ffddf65e)

**Comment by ralf-krause** [comment]
You will find infos about getting started with MicroBlocks and Linux on the web page https://microblocks.fun/get-started#computer. There you will choose the tag "Linux Setup" and "Troubleshooting".
Ralf

**Comment by ralf-krause** [comment]
Similar things must be done to connect Micro:bit and Calliope via WebUSB … you will find a topic for Linux.
https://support.microbit.org/support/solutions/articles/19000105428-webusb-troubleshooting
Yes, I think that there are correct rules for MakeCode and Arduino software in Puavo but what can‘t say if all is done the MicroBlocks or Snap4Arduino software.

**Comment by ralf-krause** [comment]
I can't say what happened. In the file etc/group I deleted the enties ralf.krause and rebooted the Puavo device. Then I tried to connect the Calliope in MicroBlocks again and it works. Also I tested the connection and programming with the guest account and on a second Puavo device.

Sorry for making trouble!
Ralf

**Comment by asokero** [comment]
Hey Ralf,

No problem. I also tried this out with microbit and it seemed to work out of the box. All the users are automatically added to the dialout group (required basically by Arduino and all the other microcontroller programming environments).

Thank you very much for active testing on all of these different devices and apps!
