### ISSUE TITLE
No German keyboard layout in the Bookworm install image

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#760]
Dear developers,

yesterday we had an admin workshop for some admins from Magdeburg. We met in the GmS Wilhelm Weitling. We had a look on the PuavoBox features which can be used by users in the school. For example the desktop links for the PuavoBox share and the personal user folder are only inside the school.

We also wanted to install a Microsoft Surface Go 3 without an ethernet connection. We wanted to install the device from an usb stick. Booting was no problem. But then we needed to enter the cryptic WiFi password. No chance. There is no German keyboard setting in the Bookworm image. Yes, it's a blocker for anyone who has no Finnish keyboard. I hope you will fix it just for the next image.

We installed the device with a Bullseye stick and this was no problem. Now I hope that the device will fetch the Bookworm image automatically. It‘s the device gsmww-go-01.magdeburg.opinsys.fi.

Best regards
Ralf

![IMG_1474](https://github.com/user-attachments/assets/8b216acf-e483-4554-86d2-f863ba52df47)

**Comment by asokero** [comment]
Thanks for reporting this, I can reproduce this and we'll take a look at it.

**Comment by asokero** [comment]
This is now fixed and seems to work in current development image. https://github.com/puavo-org/puavo-os/commit/ba814174d73b1b4c4735291b12221c7109821b73
