### ISSUE TITLE
Puavo-wlanap does not start

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#82]

**Comment by jarmopi** [comment]
Possible cause: systemd renames[0] the wlan0 interface to something else before the script executes; after the script creates the `puavowlanif0` interface but before it can be used systemd goes and renames it to `wlx<USB stick MAC>` and the script then fails completely.

This behavior can be altered/disabled in several ways. One is to create a special .link[1] file in `/etc/systemd/network`[2] that matches the wlan interface and prevents it from being renamed. This did not work properly when tested. Another way is to pass in a kernel command line argument that completely disables the renaming functionality (see [0]). This works, but now the bridge creation fails with

    systemd-udevd[4003]: Could not generate persistent MAC address for tap0: No such file or directory

and after this the bridge interface `puavowlanbr0` interface enters in blocking/disabled state.

If you repeatedly command `ip addr` after the USB stick has been inserted, you can see the relevant interfaces being created and set up, but they disappear after a few seconds.

vtund's configuration file also refers to the wlan0 interface which does not exist anymore, but changing this does not help.

[0] https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
[1] https://www.freedesktop.org/software/systemd/man/systemd.link.html
[2] We had to put the file inside a special ext4 image on the boot server and point the machine to boot from it.

**Comment by asokero** [comment]
Juhaerk fixed the rest of the problems with many commits. Its working now, I´m not kidding, it´s true.
