### ISSUE TITLE
Pairing bluetooth headphone does not work 

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#91]
For example Sony sbh70.

**Comment by asokero** [comment]
These hints at the troubleshooting section seem to fix the problem:
https://wiki.debian.org/BluetoothUser/a2dp

**Comment by Mazhoon** [comment]
Has probably been fixed for some time. Haven't encountered any problems when pairing various Bluetooth headphones in Buster and Bullseye.
