### ISSUE TITLE
Add new files in Nautilus by right clicking

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#96]
In current gnome 3 desktop only new folders can be created by right clicking but not new files. This is a small regression compared to current Trusty desktop.

**Comment by Mazhoon** [comment]
Tested template creation as described in https://askubuntu.com/questions/657320/how-to-enable-file-creation-from-nautilus-right-click-menu-on-gnome - seems to be a functional pathway to solution in bullseye

**Comment by Mazhoon** [comment]
update_templates_menu in src/nautilus-files-view.c scans (only) G_USER_DIRECTORY_TEMPLATES, which by default is 
XDG_TEMPLATES_DIR="$HOME/Templates". Would need e.g. language-specific generation of template files to the template dir on login, or assigning user template dir as something under system root.

**Comment by asokero** [comment]
This has been open for a long time and basically nobody has asked for it. Closing and let's reopen if someone actually cares.
